### PR TITLE
Set max channels separately EE and EB for ECAL

### PR DESCRIPTION
**Pull request by amassiro**
Set max channels separately EE and EB for ECAL

### CODE REVIEW

**Comment by amassiro** [comment]
Wait before merging, tests ongoing

**Comment by fwyzard** [comment]
Thanks for making PRs for both 11.1.x and 11.2.x .
I will merge the 11.1.x one, and then cherry-pick it into the 11.2.x branch (as long as there are no conflicts).

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-02:/data/user/fwyzard/patatrack/validation/run_516.5AQ8sdl0Tn ...

**Comment by fwyzard** [comment]
Fixed by #517 .

**Pull request closed without merging**
