### PR TITLE
use uint32 to index hits [do not merge]

### PR DESCRIPTION
**Pull request by VinInn**
to allow more than 64K hits we need to use a full-size int.
the size of the buffer is unchanged

The commit includes also code to count "forlorn doublets" (those that do to share any hits with tracks).
this code does not run by default

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-03:/data/user/fwyzard/patatrack/validation/run_474.V5tu23nfRa ...

**Comment by VinInn** [comment]
ok, later on I think I will have to increase the buffers as well.

**Comment by VinInn** [comment]
can we test this again with latest greatest?
ahh conflict

**Comment by mmusich** [comment]
can the history of this PR be clean-up please?

**Comment by VinInn** [comment]
I think the relevant parts of this PR are equivalent to #545

**Comment by fwyzard** [comment]
I've attempted to clean up the history and rebase the original changes on top of the current `CMSSW_11_2_X_Patatrack` branch, and pushed the result to [cms-patatrack/VinInn_Hit32](https://github.com/cms-patatrack/cmssw/tree/VinInn_Hit32).

@VinInn could you check if that's doing the right things, and in case force-push it here ?

**Comment by VinInn** [comment]
It still look a big mess.
I suggest we move to #545.

**Comment by mmusich** [comment]
This diff: https://github.com/cms-patatrack/cmssw/compare/master...cms-patatrack:VinInn_Hit32
looks simple enough... perhaps a new PR using just these commits can be created?

**Comment by VinInn** [comment]
thanks Marco.
pushed the button and done as #583


v.


> On 25 Nov, 2020, at 11:22 AM, Marco Musich <notifications@github.com> wrote:
> 
> 
> This diff: master...cms-patatrack:VinInn_Hit32
> looks simple enough... perhaps a new PR using just these commits can be created?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Il est bon de suivre sa pente, pourvu que ce soit en montant. 
A.G.
http://www.flickr.com/photos/vin60/1320965757/

**Pull request closed without merging**
