### PR TITLE
Replace AcceleratorService with HeterogeneousEDProducer

### PR DESCRIPTION
**Pull request by makortel**
Following the discussion in the Future Tracking meeting last week and after that with @fwyzard and @felicepantaleo 
https://indico.cern.ch/event/723617/#15-service-without-service-dis
this PR suggests to replace `AcceleratorService` with more framework-like `HeterogeneousEDProducer`.

This PR also extends the functionality of the "system" with
* Support for multiple GPUs
  * data location is tracked
* Hook for `beginStream*()` where the GPU algorithm should do its memory allocations and similar initialization
* The current CUDA device is set by the system before `beginStreamGPUCuda()`, `acquireGPUCuda()`, and `produceGPUCuda()`
* The system also provides the CUDA stream to use for the aforementioned functions
* The system adds the necessary callback to CUDA stream after `acquireGPUCuda()`
* Adds some documentation + TODO list to `HeterogeneousCore/README.md`
  * I intend to write more for the subpackages but didn't want to keep this PR waiting for that

There is still room for further improvements (see all TODO comments), but I think this should be now good-enough for a real test with raw2digi.

Tested in CMSSW_10_2_0_pre2.

### CODE REVIEW

**Comment by felicepantaleo** [comment]
looks good by a cursory glance. I will try to port the CA to use the HeterogeneousEDProducer once I have finished it this week and come back to you.

**Comment by felicepantaleo** [comment]
please test

**Comment by felicepantaleo** [comment]
please please test please

**Comment by felicepantaleo** [comment]
@cmsbot please test

**Comment by felicepantaleo** [comment]
@fwyzard please tell @cmsbot to please test

**Comment by makortel** [comment]
Wonderful. I'll try to find time to understand what is going on with clang.

**Comment by makortel** [comment]
@felicepantaleo 
> looks good by a cursory glance. I will try to port the CA to use the HeterogeneousEDProducer once I have finished it this week and come back to you.

Thanks!

**Comment by makortel** [comment]
> It involves the following packages:
>
> HeterogeneousCore/README.md

Hmm, maybe a `README.md` at this level is not really a good idea? The next-best location is probably `HeterogeneousCore/Producer` which is kind of most-core piece of the infrastructure.

**Comment by makortel** [comment]
We have the clang compilation problem already in `CMSSW_10_2_X_Patatrack`. In my local test the first error came from
https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/DataFormats/GeometrySurface/test/gpuFrameTransformTest.cpp
which is not touched by this PR.

The error seems to stem from clang refusing to acknowledge this `friend` declaration
https://github.com/eyalroz/cuda-api-wrappers/blob/f1b1db2cc4912d68a5da0fb964c2232804db25b3/src/cuda/api/stream.hpp#L480
after which the function
https://github.com/eyalroz/cuda-api-wrappers/blob/f1b1db2cc4912d68a5da0fb964c2232804db25b3/src/cuda/api/stream.hpp#L526-L532
can no longer access the `protected` constructor
https://github.com/eyalroz/cuda-api-wrappers/blob/f1b1db2cc4912d68a5da0fb964c2232804db25b3/src/cuda/api/stream.hpp#L475-L476

I have some ideas to play around, but my age-old recipe for building/updating externals locally seems to be out of date. Could anyone point me to a recipe/documentation on how could I update the `cuda-api-wrappers` external locally? @smuzaffar @fwyzard

**Comment by makortel** [comment]
In order to proceed in parallel, could we perhaps (continue to) ignore the clang failures for patatrack for time being?

**Comment by fwyzard** [comment]
> In order to proceed in parallel, could we perhaps (continue to) ignore the clang failures for patatrack for time being?

OK for me.

By the way, I saw some warnings from the GCC 7 build of the CUDA or Accelerator servces - could you check if we still have them with this PR ?

**Comment by makortel** [comment]
> By the way, I saw some warnings from the GCC 7 build of the CUDA or Accelerator servces - could you check if we still have them with this PR ?

Thanks for the heads-up, I'll take a look.

**Comment by makortel** [comment]
@fwyzard The warnings are still there (because the same pattern of virtual functions without virtual destructor is used, I'll add a fix here)

**Comment by makortel** [comment]
The last commit adds the virtual destructors GCC 7 was complaining about.

**Comment by makortel** [comment]
> Could anyone point me to a recipe/documentation on how could I update the cuda-api-wrappers external locally? @smuzaffar @fwyzard 

Ok, I found this twiki
https://twiki.cern.ch/twiki/bin/view/CMS/SDTExternalsWithCMSSW
which seems to be up-to-data (thanks to the usual suspects), and I managed to proceed with those instructions.

**Comment by fwyzard** [comment]
@makortel thanks for the GCC 7 fixes.
In the meantime I have made PRs to cuda-api-wrappers to
  - https://github.com/eyalroz/cuda-api-wrappers/pull/47: revert the dependency on CUB
  - https://github.com/eyalroz/cuda-api-wrappers/pull/48: change the friend declaration to make clang happy

Once the latter has been reviewed and merged, I will update (again) the external for CMSSW.

However, building with llvm/clang still fails because of some template parameters not being constexpr. I think this is a bug in clang, but I have not been able to reproduce it with a minimal test case.

**Comment by makortel** [comment]
@fwyzard Excellent, thanks! (https://github.com/eyalroz/cuda-api-wrappers/pull/48 was what I suspected as well, but ran out of time before managing to test it)

**Pull request merged**
