### PR TITLE
Ecal Reco with CUDA: Attempt to Optimize 

### PR DESCRIPTION
**Pull request by vkhristenko**
This pr supersedes the previous one on ecal, #267 

not 100% identical results yet, but wanted to get some feedback and suggestions further.
all updates come from the last commit 78cb86b

I did the following
- split monolithic kernel into 3 (at least 3 for now) according to how memory is being used and how parallelism can be used.
- remove code that is not used at all
- all eigen stuff should now be static, unless i missed something
- clean up minimization procedure _kernel minimize is the most time consuming part_

results do not match 100% yet, 

screen shot 2019-03-04 at 2 46 09 pm

The crude runtime i observe for 2018 data 
```
TimeReport   0.228660     0.228660     0.228660  ecalMultiFitUncalibRecHit
TimeReport   0.031554     0.031554     0.031554  ecalMultiFitUncalibRecHitgpu
```

and for 2017 data
```
TimeReport   0.055629     0.055629     0.055629  ecalMultiFitUncalibRecHit
TimeReport   0.012366     0.012366     0.012366  ecalMultiFitUncalibRecHitgpu
```

but that does not include timing computation. numbers can be improved further.

At this point, i want to get fit amplitudes match 100% preserving this runtime and then work on further optimizations. I wanted to ask if there are any  suggestions (in particular for minimize)... __this is work in progress__.

### CODE REVIEW

**Comment by amassiro** [comment]
For some channels good correlation between two reconstructions, some other ones no.
See attached plot: left EE, right EB

screenshot from 2019-03-04 18-06-02

**Comment by fwyzard** [comment]
@vkhristenko @amassiro 
can you point me to
1. a workflow that run only ECAL local reco on cpu
2. a workflow that runs only ECAL local reco un gpu
3. a way to make vaiidation plots (for MC and/or data) 

?

I would like to start adding them to the usual Patatrack validation.

**Comment by amassiro** [comment]
Cfg:
1. https://github.com/amassiro/EcalLocalRecoToolKit/blob/master/test/gpu/raw2digi_ecalonly_cpuonly.py
2. https://github.com/amassiro/EcalLocalRecoToolKit/blob/master/test/gpu/raw2digi_ecalonly_gpuonly.py

and to use them:

```
export CUDA_VISIBLE_DEVICES=1;    cmsRun raw2digi_newFormat_gpu_ecalonly.py       inputType=globalRun          year=2017    
   
 cmsRun raw2digi_newFormat_cpu_ecalonly.py       inputType=globalRun          year=2017    

```    

For the 3, do you mean something to get plots like the following?

Screenshot from 2019-03-14 12-47-55

**Comment by vkhristenko** [comment]
superseded by #313

**Pull request closed without merging**
