### PR TITLE
Fix MTV validation of initialStepPreSplitting tracks

### PR DESCRIPTION
**Pull request by makortel**
Merges https://github.com/cms-sw/cmssw/pull/25346 on top of CMSSW_10_4_X_Patatrack.

This should fix the weird results @VinInn saw when using GPU clusters in initialStepPreSplitting.

### CODE REVIEW

**Comment by VinInn** [comment]
I think it clashes with  #193
I get for instance
```
    tracksValidationTruthPixelTrackingOnly += trackingParticlesBHadron
TypeError: unsupported operand type(s) for +=: 'Task' and 'EDProducer'
```

**Comment by makortel** [comment]
Let me make a combined PR then.

**Comment by makortel** [comment]
@VinInn #199 combines this PR and #193.

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.cH3lSTInf2 ...

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.C7danRFfeh ...

**Comment by fwyzard** [comment]
Included via #199

**Pull request closed without merging**
