### PR TITLE
Ecal Validation: add bitwise comparison plots

### PR DESCRIPTION
**Pull request by vkhristenko**
- Add bit-wise comparison and plots for `amplitude` and `chi2` variables
[ecal-amplitudes.pdf](https://github.com/cms-patatrack/cmssw/files/3325044/ecal-amplitudes.pdf)
[ecal-chi2.pdf](https://github.com/cms-patatrack/cmssw/files/3325045/ecal-chi2.pdf)

### CODE REVIEW

**Comment by fwyzard** [comment]
could you explain how to read the new plots ?
what do they have on the X axis ?

**Comment by fwyzard** [comment]
do the 32 values show how often each bit is different between cpu and gpu ?

**Comment by vkhristenko** [comment]
yep,
- value = 32bit_cpu xor 32bit_gpu
- for each bit of value, fill hist for the bin corresponding to the bit if this bit is 1

this bit-wise correspondance will need to be shown i guess...

**Comment by fwyzard** [comment]
ok, now I understand better the technical aspects...
I don't know how much this kind of comparison will be useful, but I would let @amassiro comment on that !

**Comment by fwyzard** [comment]
(I mean, when we say "bitwise agreement" I think for a float we just mean the delta instead of a binned comparison)

**Comment by vkhristenko** [comment]
I think it depends who you talk to :)

**Comment by fwyzard** [comment]
As expected, comparing the GPU results in SoA format with the same results converted to legacy format yields identical results.

**Pull request closed without merging**
