### PR TITLE
Add missing inline keywords to cudautils::launch

### PR DESCRIPTION
**Pull request by fwyzard**
This is part of the proposed changes from #428 .

### CODE REVIEW

**Comment by makortel** [comment]
The `launch.h` is part of https://github.com/cms-sw/cmssw/pull/28537. @fwyzard, do you agree that I should just cherry-pick the commit there as well (instead of a subsequent PR)?

**Comment by fwyzard** [comment]
Sure.

**Comment by fwyzard** [comment]
By the way, `clang-format` does not seem happy about this file, but I would rather not make the proposed changes:
```diff
diff --git a/HeterogeneousCore/CUDAUtilities/interface/launch.h b/HeterogeneousCore/CUDAUtilities/interface/launch.h
index fbf67fbdc59..a72c6a9b6c0 100644
--- a/HeterogeneousCore/CUDAUtilities/interface/launch.h
+++ b/HeterogeneousCore/CUDAUtilities/interface/launch.h
@@ -100,11 +100,11 @@ namespace cudautils {
   template <typename F, typename... Args>
   inline
 #if __cplusplus >= 201703L
-  std::enable_if_t<std::is_invocable_r<void, F, Args&&...>::value>
+      std::enable_if_t<std::is_invocable_r<void, F, Args&&...>::value>
 #else
-  std::enable_if_t<std::is_void<std::result_of_t<F && (Args && ...)> >::value>
+      std::enable_if_t<std::is_void<std::result_of_t<F && (Args && ...)> >::value>
 #endif
-  launch(F* kernel, LaunchParameters config, Args&&... args) {
+      launch(F* kernel, LaunchParameters config, Args&&... args) {
     using function_type = detail::kernel_traits<F>;
     typename function_type::argument_type_tuple args_copy(args...);
 
@@ -126,11 +126,11 @@ namespace cudautils {
   template <typename F, typename... Args>
   inline
 #if __cplusplus >= 201703L
-  std::enable_if_t<std::is_invocable_r<void, F, Args&&...>::value>
+      std::enable_if_t<std::is_invocable_r<void, F, Args&&...>::value>
 #else
-  std::enable_if_t<std::is_void<std::result_of_t<F && (Args && ...)> >::value>
+      std::enable_if_t<std::is_void<std::result_of_t<F && (Args && ...)> >::value>
 #endif
-  launch_cooperative(F* kernel, LaunchParameters config, Args&&... args) {
+      launch_cooperative(F* kernel, LaunchParameters config, Args&&... args) {
     using function_type = detail::kernel_traits<F>;
     typename function_type::argument_type_tuple args_copy(args...);
 
```

**Comment by makortel** [comment]
All that because of the added inline?

**Comment by fwyzard** [comment]
Yep...

Shall I remove it ?
It should be anyway redundant in a `template` function.

**Comment by fwyzard** [comment]
Removed it :)

**Pull request merged**
