### PR TITLE
Riemann fit patatrack

### PR DESCRIPTION
**Pull request by rovere**
This will bring in the current status of the Riemann fit, i.e.

* On the CPU mostly working except for MS in linear fit + tuning of residuals on pt
* On the GPU: a standalone test of a single Riemann fit (modulo matrix inversion which is avoided turning off, for the time being, error propagation).This requires a patch to Eigen.

The riemannFit modifier has been implemented for the CPU so that workflows 10824.5 and 10824.7 are identical but for the Fitting component.

### CODE REVIEW

**Comment by fwyzard** [comment]
@rovere I am getting a huge amount of warnings from eigen even when I'm not building the GPU test file.
Do you know what is their source ?

**Comment by rovere** [comment]
@fwyzard not sure, but I bet they are coming from RiemannFit.h?

**Comment by fwyzard** [comment]
Indeed
```
/data2/fwyzard/patatrack/CMSSW_10_1_X_Patatrack/src/RecoPixelVertexing/PixelTrackFitting/interface/RiemannFit.h(557): warning: calling a __host__ function from a __host__ __device__ function is not allowed
```
and then 300 more within Eigen itself.

I will try with the patched Eigen, but we need a workaround for the warnings :-(

**Comment by fwyzard** [comment]
After some hours of searching, I have not found any solutions, and only a not very satisfactory workaround: passing `-w` to nvcc to silence the warning...

**Comment by fwyzard** [comment]
An other possibility, used by other projects for a similar reason, is to mark the relevant functions with
```c++
#pragma hd_warning_disable
```
or
```c++
#pragma nv_exec_check_disable
```

Unfortunately,  both are undocumented as far as I can tell, so the effect is not completely clear.
There is also kind of a bug report related to `#pragma hd_warning_disable` and Eigen...

**Comment by fwyzard** [comment]
Some example of using those pragmas:
  - https://github.com/BaderLab/ecuda/blob/master/include/ecuda/global.hpp#L51_L59
  - https://gitlab.kitware.com/vtk/vtk-m/blob/master/vtkm/internal/ExportMacros.h#L32
  - CUDA's own `include/crt/nvfunctional`

**Comment by fwyzard** [comment]
Here is a possible outcome I would envision for the automatic comparison:
  - [RelValZMM_13-CMSSW_10_1_0_pre2-100X_upgrade2018_realistic_v11-v1 sample](http://fwyzard.web.cern.ch/fwyzard/patatrack/pull34/RelValZMM_13-CMSSW_10_1_0_pre2-100X_upgrade2018_realistic_v11-v1/plots/)
  - [RelValTTbar_13-CMSSW_10_1_0_pre2-PU25ns_100X_upgrade2018_realistic_v11-v1](http://fwyzard.web.cern.ch/fwyzard/patatrack/pull34/RelValTTbar_13-CMSSW_10_1_0_pre2-PU25ns_100X_upgrade2018_realistic_v11-v1/plots/)

I don't have a way to automate running and making the plots yet, however I do have a script to setup and build the various releases, run the various workflows, and make these comparison plots (based on `makeTrackingPlots.py`).

The script now runs
  - workflow `10824.5` (pixel tracking) for the `referencence` release, currently `CMSSW_10_1_0_pre2`
  - workflows `10824.5`, `10824.7` (pixel tracking with Riemann fit), `10824.8` (pixel tracking on the GPU) with the reference release plus the `HEAD` cms-patatrack branch (currently `CMSSW_10_1_X_Patatrack`)
  - workflows `10824.5`, `10824.7` and `10824.8` with the same branch plus the PR begin tested

over 100 events from two datasets: Zmumu MC without pileup, and ttbar with pileup, and takes about 30-40 minutes to complete.

I'm happy to hear suggestions about
  - what workflows we should run 
  - what dataset we should use (I would like to add 2017 data, but we need a different way to look at the results)
  - how many events to run
  - whether the comparison can be improved or extended making use of a (local ?) DQM GUI instead
  - anything else you can think of

**Comment by fwyzard** [comment]
P.S. why does the tracks' eta look so broken ? Is it a problem with the pre2 samples ?

**Comment by fwyzard** [comment]
@rovere , if I trust the plots on the [Z→μμ sample](http://fwyzard.web.cern.ch/fwyzard/patatrack/pull34/RelValZMM_13-CMSSW_10_1_0_pre2-100X_upgrade2018_realistic_v11-v1/plots/plots_pixelTrack_pixel/pulls.pdf), comparing the green (Riemann fit) vs red or magenta (standard pixel tracking), I would say that
  - the pT pull is much better
  - the phi and dxy pulls are somewhat better
  - the eta and dz pulls are much worse

The effect is event bigger in the [ttbar sample](http://fwyzard.web.cern.ch/fwyzard/patatrack/pull34/RelValTTbar_13-CMSSW_10_1_0_pre2-PU25ns_100X_upgrade2018_realistic_v11-v1/plots/plots_pixelTrack_pixel/pulls.pdf).

Is it expected ?

**Comment by rovere** [comment]
Yes, that's expected and Roberto Ribatti is working on the last pulls.



Ciao,
-- Marco.

___________
Marco Rovere
Marco.Rovere@cern.ch
CERN EP-CMG | room 40 3-A28 | tel +41227671209 (71209)

**Comment by makortel** [comment]
@fwyzard 
> P.S. why does the tracks' eta look so broken ? Is it a problem with the pre2 samples ?

Could you be more specific? I took a look on efficiency+fake+duplicate rates vs eta for ttbar+PU and everything looks fine to me.

**Comment by fwyzard** [comment]
> I took a look on efficiency+fake+duplicate rates vs eta for ttbar+PU and everything looks fine to me.

Indeed, sorry fr the noise. I swapped the "efficiency" and "fakses" plots.

**Comment by makortel** [comment]
> * what workflows we should run

I'd say your current selection (ZMM, ttbar+PU) is pretty good.

(high-pT jets, i.e. QCD pThat 600-800 or flat pThat 15-3000 would be the next sample on my list, but this has to be balanced with how much time we want to spend on the tests)

> * what dataset we should use (I would like to add 2017 data, but we need a different way to look at the results)

At least JetHT. Maybe SingleMuon as well?

> * how many events to run

I've usually run 1000 ttbar+PU events for full tracking testing and found that good-enough for most of the time. But that would be 10x increase compared to your test, so would take too long to run.

For efficiencies, fakes, and overall pulls the 100 events seem to be enough. Apparently also differential resolutions in ttbar+PU (ok, PU tracks help to increase statistics), but not really for differential resolutions in ZMM. On the other hand ZMM noPU should be pretty fast to run so the number of events could be probably be increased? (by how much I don't know, would need some experimentation)

> * whether the comparison can be improved or extended making use of a (local ?) DQM GUI instead

At least the GUI would allow to dig in details that are not shown by `makeTrackValidationPlots.py` (and would be needed for data unless we extend `makeTrackValidationPlots.py` to cover also some of the DQM histograms).

The downside with pure GUI is that the "standard" efficiency+fake+duplicate plots vs. pT+eta+phi etc take a bit more effort to take a look. So maybe extend with GUI?

> * anything else you can think of

The current set of 7 comparisons is rather busy to interpret (and GUI supports up to 5 DQM files). Below I try to think out loud which kind of comparison combinations I would be interested to take a look (it was more difficult than I thought)
* 10824.5 (ref release), 10824.5 (patatrack), 10824.7 (patatrack), 10824.8 (patatrack)
* 10824.5 (ref release), 10824.5 (PR), 10824.7 (PR), 10824.8 (PR)
* 10824.5 (patatrack), 10824.5 (PR)
* 10824.7 (patatrack), 10824.7 (PR)
* 10824.8 (patatrack), 10824.8 (PR)

This is where the DQM GUI approach would shine, since one can easily "generate" a new comparison by just modifying the URL.

**Comment by fwyzard** [comment]
@makortel thanks for the comments.

Indeed Zmumu can be run with higher statistics - I've increased it to 200 events, and probably 500 is still OK.

Let's see if I can convince @rovere to help me use a DQM GUI...

**Comment by rovere** [comment]
We agreed already on using one.



Ciao,
-- Marco.

___________
Marco Rovere
Marco.Rovere@cern.ch
CERN EP-CMG | room 40 3-A28 | tel +41227671209 (71209)

**Pull request merged**
