### PR TITLE
Make a local copy of CUB's CachingDeviceAllocator and patch it for the race condition

### PR DESCRIPTION
**Pull request by makortel**
As discussed in #237.

### CODE REVIEW

**Comment by fwyzard** [comment]
No changes in physics performance (as expected):

RelValTTbar_13 | reference-10824.5 | development-10824.5 | development-10824.8 | testing-10824.8
-- | -- | -- | -- | --
Efficiency | 0.4818 | 0.4824 | 0.4842 | 0.4842
Number of TrackingParticles (after cuts) | 5556 | 5556 | 5556 | 5556
Number of matched TrackingParticles | 2677 | 2680 | 2690 | 2690
Fake rate | 0.0519 | 0.0517 | 0.0337 | 0.0337
Duplicate rate | 0.0168 | 0.0175 | 0.0176 | 0.0176
Number of tracks | 32452 | 32480 | 31796 | 31796
Number of true tracks | 30769 | 30801 | 30723 | 30724
Number of fake tracks | 1683 | 1679 | 1073 | 1072
Number of pileup tracks | 27093 | 27118 | 26998 | 26998
Number of duplicate tracks | 546 | 567 | 559 | 559

**Comment by fwyzard** [comment]
No changes in throughput:
#### before
```
Warming up
Running 4 times over 4200 events with 1 jobs, each with 8 threads, 8 streams and 1 GPUs
  1730.3 ±   1.8 ev/s (4000 events)
  1726.9 ±   2.4 ev/s (4000 events)
  1731.3 ±   1.4 ev/s (4000 events)
  1738.8 ±   1.3 ev/s (4000 events)
```
#### after
```
Warming up
Running 4 times over 4200 events with 1 jobs, each with 8 threads, 8 streams and 1 GPUs
  1726.4 ±   2.6 ev/s (4000 events)
  1734.6 ±   1.8 ev/s (4000 events)
  1725.1 ±   1.8 ev/s (4000 events)
  1729.6 ±   2.0 ev/s (4000 events)
```

**Comment by fwyzard** [comment]
Given the simple commit history, I have tried merging this PR using the "Rebase and merge" approach instead of the usual "Squash and merge".

The positive aspect is that it keeps the full git log history, i.e. it looked like this:
* 5579cacfa29a Move mutex unlock after the cudaEventRecord() in DeviceFree()
* 9781dcf1d423 Include local copy of CachingDeviceAllocator
* eae2fbc643e3 Set the data pointer of error's SimpleVector (#236)
* ebc280c9d24e Fix a race for CUDA event in CachingHostAllocator (#237)
* ...

The negative aspect is that there is no trace of the PR number in the git log.
As part of the test, I have fixed that locally and force-pushed the update, so the history now looks like this:
* 68f320f5122e Move mutex unlock after the cudaEventRecord() in DeviceFree() (#240)
* 096e0e3aa83b Include local copy of CachingDeviceAllocator (#240)
* eae2fbc643e3 Set the data pointer of error's SimpleVector (#236)
* ebc280c9d24e Fix a race for CUDA event in CachingHostAllocator (#237)
* ...

What do people like best ?
  - squash into a single commit (I would still do this for very long commit histories)
  - rebase
  - rebase and reword to add the PR number
  - merge (as done in the upstream CMSSW)

**Comment by rovere** [comment]
Ciao @fwyzard 
I'm not sure I understand the difference between the rebase+reword and the usual merge approach.
Having the PR is, IMHO, very useful. I'd actually go one step further and add the username of the requester together with the PR number (also for our upstream CMSSW repository).

**Comment by makortel** [comment]
I'd prefer squash or rebase over the merge (since we're not the upstream repo, and "random" merges tend to make the history, and later comparisons/ports to upstream more difficult). I also think the PR number in the commit message(s) do(es) have some value (especially since we have those already in the history). So I suppose my preference would be 
* rebase and reword when "it makes sense" to preserve the commit history of a PR
* otherwise squash

**Comment by fwyzard** [comment]
@makortel thanks for your comments, I think I agree with you.
Rebasing + rewording takes a bit of manual effort, so I'd reserve it for the cases where I think it makes most sense.

**Pull request merged**
