### PR TITLE
Ecal rechit on GPU, 11_1_X

### PR DESCRIPTION
**Pull request by amassiro**
From uncalibrated rechit to rechit on GPU, in CMSSW_11_1_X

The PR includes validation code for rechit comparison, similar to what shown at ECAL DPG meeting.

Some to the files changed are just "c++ stylistic", it can be reversed (I needed to debug).

### CODE REVIEW

**Comment by fwyzard** [comment]
Mhm... can you rebase on the current HEAD ?

I think the commits up to b21427c  are already merged.
If it's easier, you could just fix the conflicts locally, and squash the whole to a single commit.

**Comment by amassiro** [comment]
> Mhm... can you rebase on the current HEAD ?
> 
> I think the commits up to [b21427c](https://github.com/cms-patatrack/cmssw/commit/b21427c6d505b2c6780fde61cffbec7c173a5585) are already merged.
> If it's easier, you could just fix the conflicts locally, and squash the whole to a single commit.

sure, let me try that

**Comment by fwyzard** [comment]
Should this be closed in favour of #462 ?

**Comment by amassiro** [comment]
Superseeded by https://github.com/cms-patatrack/cmssw/pull/462

**Pull request closed without merging**
