### PR TITLE
Move event and stream caches, and caching allocators out from CUDAService

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR moves the CUDA event and stream caches, and the device and pinned-host caching allocators out from CUDAService. Motivations include
* simpler code: no need to create `edm::Service<CUDAService>` for allocation or for cached streams/events
   * especially helpful in tests where previously the whole PluginManager infrastructure was needed
* allows memory allocation in "module-internal tasks" for which helpers are introduced in #363 (without having to enable edm::Services in these tasks)
* framework group wants to reduce the amount of service handles (`edm::Service<T>`) in CMSSW

#### PR validation:

Profiling workflow runs, unit test run.

### CODE REVIEW

**Comment by makortel** [comment]
Conflicts with #363 and #362 (maybe easier to merge them first and then rebase this one).

**Comment by makortel** [comment]
Fixed a bug effectively leading to no caching.

**Comment by fwyzard** [comment]
> framework group wants to reduce the amount of service handles (`edm::Service<T>`) in CMSSW

I'm mostly fine with the change, and indeed the Services were supposed to be "optional", not to provide essential functionality; can you (or the framework group) share some idea on how can we "configure" these global objects ?

For example, how can one disable the caching allocator altogether, to let the CUDA memory tools catch uninitialised memory errors ?

Then, just out of curiosity, why `edm::Service<T>` are now Bad™ ?
Global, singleton-like objects were initially hailed as something to be avoided; why they are now Good™ (or good enough) ?

**Comment by makortel** [comment]
> For example, how can one disable the caching allocator altogether, to let the CUDA memory tools catch uninitialised memory errors ?

In this PR the caching can be disabled at compile time. Would you like it to stay as runtime configurable?

**Comment by fwyzard** [comment]
Depends how much of the user code needs to be rebuilt :-)

But it was more of a general question about migrating away from services.

**Comment by makortel** [comment]
> Depends how much of the user code needs to be rebuilt :-)

In this case it would be a couple of files in `HeterogeneousCore/CUDAServices/src` and `CUDAService`. The compile-time configuration options are not exposed to users.

> can you (or the framework group) share some idea on how can we "configure" these global objects ?

At the moment the "best" option is to deliver the runtime-configurable parameters from a Service to the global object (obviously via other means than the constructor of the global object, at least when the globalness is implemented as a function-local static).

> Then, just out of curiosity, why edm::Service<T> are now Bad™ ?
> Global, singleton-like objects were initially hailed as something to be avoided; why they are now Good™ (or good enough) ?

It depends on what exactly the "global object" does. The main drawback of the Service infrastructure is that it is rather complex, and requires special setup to be enabled, which makes them more laborious to be used in tests and in arbitrary TBB tasks.

So it is not that there is or would be a major campaign to transform Services to something else, but rather a question whether all current uses of Services (especially with the handles) really the proper use of Services. And yes, sometimes it is difficult to judge. E.g. here I'm not 100 % sure if making these caches global is the best option, but these should be taken away from CUDAService (for the Service complexity reasons) and being globals is the somewhat simplest step (that my need to be re-evaluated at some point).

**Comment by fwyzard** [comment]
:construction: Validation running at workergpu10:/mnt/home/fwyzard/validation/run.BIzDVe5dZb ...

**Comment by makortel** [comment]
Rebased on top of HEAD (#385). Profiling workflow runs. I'm still running unit tests.

**Comment by fwyzard** [comment]
@makortel I hope I fixed the conflicts correctly; could you double check ?

**Comment by fwyzard** [comment]
> @makortel I hope I fixed the conflicts correctly; could you double check ?

Mhm, probably not, since I get a segmentation fault in `testHeterogeneousCoreCUDACore` and `testHeterogeneousCoreCUDATest`, and a failed assert in `TestCUDATest` :-(

**Comment by fwyzard** [comment]
Actually, I see these also with this PR applied on top of the HEAD pre-#363:
> ---> test TestCUDATest had ERRORS
> ---> test testHeterogeneousCoreCUDATest had ERRORS

**Comment by fwyzard** [comment]
And the crash in `testHeterogeneousCoreCUDACore` is there as well in the unmodified PR.
However (both with and without #363) it is just not 100% reproducible:
```bash
fwyzard@hilton-c2e36-35-04:.../CMSSW_10_6_0_Patatrack/test/slc7_amd64_gcc700$ while ./testHeterogeneousCoreCUDACore; do true; done
===============================================================================
All tests passed (16 assertions in 1 test case)

===============================================================================
All tests passed (16 assertions in 1 test case)


 *** Break *** segmentation violation

...

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f47db7faa87 in ?? () from /lib64/libcuda.so.1
#7  0x00007f47db703f65 in ?? () from /lib64/libcuda.so.1
#8  0x00007f47db84ac22 in cuStreamDestroy_v2 () from /lib64/libcuda.so.1
#9  0x00007f47dcfc80d0 in ?? () from /data/user/fwyzard/patatrack/CMSSW_10_6_0_Patatrack/external/slc7_amd64_gcc700/lib/libcudart.so.10.1
#10 0x00007f47dd006aad in cudaStreamDestroy () from /data/user/fwyzard/patatrack/CMSSW_10_6_0_Patatrack/external/slc7_amd64_gcc700/lib/libcudart.so.10.1
#11 0x00007f47de77a5d7 in cuda::stream_t<false>::~stream_t (this=0x1a8c7e0, __in_chrg=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/external/cuda-api-wrappers/20180504-pafccj4/include/cuda/api/stream.hpp:459
#12 0x00007f47de77b068 in edm::ReusableObjectHolder<cuda::stream_t<false> >::~ReusableObjectHolder (this=0x1a95980, __in_chrg=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0_Patatrack/src/FWCore/Utilities/interface/ReusableObjectHolder.h:87
#13 std::_Destroy<edm::ReusableObjectHolder<cuda::stream_t<false> > > (__pointer=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/external/gcc/7.0.0-pafccj/include/c++/7.4.1/bits/stl_construct.h:98
#14 std::_Destroy_aux<false>::__destroy<edm::ReusableObjectHolder<cuda::stream_t<false> >*> (__last=<optimized out>, __first=0x1a95980) at /data/cmssw/slc7_amd64_gcc700/external/gcc/7.0.0-pafccj/include/c++/7.4.1/bits/stl_construct.h:108
#15 std::_Destroy<edm::ReusableObjectHolder<cuda::stream_t<false> >*> (__last=<optimized out>, __first=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/external/gcc/7.0.0-pafccj/include/c++/7.4.1/bits/stl_construct.h:137
#16 std::_Destroy<edm::ReusableObjectHolder<cuda::stream_t<false> >*, edm::ReusableObjectHolder<cuda::stream_t<false> > > (__last=0x1a959a0, __first=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/external/gcc/7.0.0-pafccj/include/c++/7.4.1/bits/stl_construct.h:206
#17 std::vector<edm::ReusableObjectHolder<cuda::stream_t<false> >, std::allocator<edm::ReusableObjectHolder<cuda::stream_t<false> > > >::~vector (this=0x7f47de7854d0 <cudautils::getCUDAStreamCache()::cache>, __in_chrg=<optimized out>) at /data/cmssw/slc7_amd64_gcc700/external/gcc/7.0.0-pafccj/include/c++/7.4.1/bits/stl_vector.h:434
#18 cudautils::CUDAStreamCache::~CUDAStreamCache (this=0x7f47de7854d0 <cudautils::getCUDAStreamCache()::cache>, __in_chrg=<optimized out>) at /data/user/fwyzard/patatrack/CMSSW_10_6_0_Patatrack/src/HeterogeneousCore/CUDAUtilities/interface/CUDAStreamCache.h:13
#19 0x00007f47da339a69 in __run_exit_handlers () from /lib64/libc.so.6
#20 0x00007f47da339ab5 in exit () from /lib64/libc.so.6
#21 0x00007f47da322c0c in __libc_start_main () from /lib64/libc.so.6
#22 0x000000000043475a in _start ()
===========================================================
```

**Comment by fwyzard** [comment]
As a final cross-check, all unit tests reproducibly pass without this PR.

**Comment by makortel** [comment]
Everything worked yesterday on top of #385. Let me rebase again.

**Comment by makortel** [comment]
Rebased on top of HEAD (#363). Profiling workflow and unit tests work on `felk40`.

**Comment by fwyzard** [comment]
Thanks, this has fixed the issues on the T4 as well.

**Comment by makortel** [comment]
@vkhristenko This PR may affect your PRs.

**Pull request merged**
