### PR TITLE
Fix MTV validation of initialStepPreSplitting tracks and add B-hadron MTV variation to pixel track validation sequence

### PR DESCRIPTION
**Pull request by makortel**
This PR is a combination of #198 and #193 (to address the merge conflics).

### CODE REVIEW

**Comment by VinInn** [comment]
got 
```
An exception of category 'InvalidReference' occurred while
   [0] Processing  Event run: 1 lumi: 150 event: 7453 stream: 2
   [1] Running path 'prevalidation_step'
   [2] Prefetching for module MultiTrackValidator/'trackValidatorTrackingOnly'
   [3] Prefetching for module VertexAssociatorByPositionAndTracksProducer/'VertexAssociatorByPositionAndTracks'
   [4] Calling method for module TrackAssociatorEDProducer/'trackingParticleRecoTrackAsssociation'
Exception Message:
ClusterTPAssociation has TrackingParticles with ProductID 32577:0, but got TrackingParticleRef/Handle/ProductID with ID 3:823. This is typically caused by a configuration error.
-
```

I remind that I only added
```
from RecoPixelVertexing.PixelTriplets.caHitQuadrupletHeterogeneousEDProducer_cfi import caHitQuadrupletHeterogeneousEDProducer as _caHitQuadrupletHeterogeneousEDProducer
process.initialStepHitQuadrupletsPreSplitting = _caHitQuadrupletHeterogeneousEDProducer.clone()
process.initialStepHitQuadrupletsPreSplitting.trackingRegions = "initialStepTrackingRegions"
```

to a standard reco dqm config (with  Run2_2018,gpu)

**Comment by VinInn** [comment]
the standard tkreco dqm gives
```
----- Begin Fatal Exception 27-Nov-2018 09:30:29 CET-----------------------
An exception of category 'NotFound' occurred while
   [0] Calling beginStream for module ClusterTPAssociationHeterogeneous/'tpClusterProducerHeterogeneousPreSplitting'
Exception Message:
Service Request unable to find requested service with compiler type name ' 11CUDAService'.
----- End Fatal Exception -------------------------------------------------
```

something wrong, maybe in the merge
I will try with a virgin area w/o my PR...

**Comment by VinInn** [comment]
ok, 
adding
```
process.load('HeterogeneousCore.CUDAServices.CUDAService_cfi')
```
fix the cpu wf. maybe it has always been the case, not sure

**Comment by VinInn** [comment]
Ok, after merging and remerging #197 and this PR it seems running...
will post the result when ready....

**Comment by VinInn** [comment]
it makes much more sense now!
http://innocent.home.cern.ch/innocent/RelVal/ttbarPU50_gpuSeeds/plots_seeding_seeds_initialStepPreSplitting/effandfakePtEtaPhi.pdf

**Comment by makortel** [comment]
@VinInn Great!

**Comment by VinInn** [comment]
Fixed the reference as well... (same link)
the one with the buggy reference is moved to
http://innocent.home.cern.ch/innocent/RelVal/ttbarPU50_gpuSeedsBuggy/plots_seeding_seeds_initialStepPreSplitting/effandfakePtEtaPhi.pdf

**Comment by makortel** [comment]
Interesting that GPU workflow gives so much higher efficiency.

**Comment by VinInn** [comment]
and zero fakes/duplicates...
I know exactly why  (cuts too tight in FPIX)

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.3d7ta410gu ...

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.1Fx6fmCJys ...

**Comment by fwyzard** [comment]
@makortel with #193 I get a summary that looks [like this](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/7a778d9b9afafd06484a9c0d90bb7665c67ebb7e/RelValTTbar_13-CMSSW_10_4_0_pre2-PU25ns_103X_upgrade2018_realistic_v8-v1/10824.5/plots_summary.html):
image
while with this PR I get something [like this](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/df54e84387e5e3ee75936e5b88fa354e72ed6e4e/RelValTTbar_13-CMSSW_10_4_0_pre2-PU25ns_103X_upgrade2018_realistic_v8-v1/10824.5/plots_summary.html):
image

Did we loose the `Pixel tracks (B-hadron TPs)` part ?

**Comment by makortel** [comment]
> Did we loose the Pixel tracks (B-hadron TPs) part ?

A copy-paste mistake when resolving the conflict between #198 and #193, hopefully fixed with the last commit. Thanks for spotting!

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.ruJlUI4LMt ...

**Comment by fwyzard** [comment]
In the meantime, I'm looking at the 2423 [initcheck errors](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/df54e84387e5e3ee75936e5b88fa354e72ed6e4e/RelValTTbar_13-CMSSW_10_4_0_pre2-PU25ns_103X_upgrade2018_realistic_v8-v1/testing-10824.8-cuda-initcheck.log)...

Looking at the first one
```
========= CUDA-MEMCHECK
========= Host API memory access error at host access to 0x761720000 of size 112660 bytes
=========     Uninitialized access at 0x761731720 on access by cudaMemcopy source.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/lib64/libcuda.so.1 (cuMemcpyAsync + 0x1b9) [0x24b4e9]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_4_0_pre2_Patatrack/external/slc7_amd64_gcc700/lib/libcudart.so.10.0 [0x3738d]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_4_0_pre2_Patatrack/external/slc7_amd64_gcc700/lib/libcudart.so.10.0 [0x14643]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_4_0_pre2_Patatrack/external/slc7_amd64_gcc700/lib/libcudart.so.10.0 (cudaMemcpyAsync + 0x176) [0x52a66]
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run.1Fx6fmCJys/testing/lib/slc7_amd64_gcc700/pluginRecoLocalTrackerSiPixelClusterizerPlugins.so (_ZN15pixelgpudetails28SiPixelRawToClusterGPUKernel17makeClustersAsyncEPK23SiPixelFedCablingMapGPUPKhPK22SiPixelGainForHLTonGPURKNS0_15WordFedAppenderEjjbbbbbRN4cuda8stream_tILb0EEE + 0x1d87) [0x6e827]
...
```
with `objdump` gives
```
$ objdump -d -S -l .../lib/slc7_amd64_gcc700/pluginRecoLocalTrackerSiPixelClusterizerPlugins.so | grep -B15 -A5 '6e827:'
   6e7ef:       48 8b bd b8 fb ff ff    mov    -0x448(%rbp),%rdi
   6e7f6:       ba 03 00 00 00          mov    $0x3,%edx
   6e7fb:       48 89 fe                mov    %rdi,%rsi
   6e7fe:       ff d0                   callq  *%rax
.../src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu:625
        cudaCheck(cudaMemcpyAsync(digis_clusters_h.adc.get(), digis_d.adc(), wordCounter*sizeof(uint16_t), cudaMemcpyDefault, stream.id()));
   6e800:       48 8b 95 a0 fb ff ff    mov    -0x460(%rbp),%rdx
   6e807:       48 8b b3 90 01 00 00    mov    0x190(%rbx),%rsi
   6e80e:       b9 04 00 00 00          mov    $0x4,%ecx
   6e813:       48 8b bb f0 00 00 00    mov    0xf0(%rbx),%rdi
   6e81a:       4d 8b 44 24 08          mov    0x8(%r12),%r8
   6e81f:       48 01 d2                add    %rdx,%rdx
   6e822:       e8 29 79 fc ff          callq  36150 <cudaMemcpyAsync@plt>
_Z10cudaCheck_PKciS0_9cudaError():
.../src/HeterogeneousCore/CUDAUtilities/interface/cudaCheck.h:28
   6e827:       85 c0                   test   %eax,%eax
   6e829:       0f 85 fd 14 00 00       jne    6fd2c <_ZN15pixelgpudetails28SiPixelRawToClusterGPUKernel17makeClustersAsyncEPK23SiPixelFedCablingMapGPUPKhPK22SiPixelGainForHLTonGPURKNS0_15WordFedAppenderEjjbbbbbRN4cuda8stream_tILb0EEE+0x328c>
_ZN15pixelgpudetails28SiPixelRawToClusterGPUKernel17makeClustersAsyncEPK23SiPixelFedCablingMapGPUPKhPK22SiPixelGainForHLTonGPURKNS0_15WordFedAppenderEjjbbbbbRN4cuda8stream_tILb0EEE():
...src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu:634
       std::cout
         << "CUDA countModules kernel launch with " << blocks
```
points to
```
/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu:625
        cudaCheck(cudaMemcpyAsync(digis_clusters_h.adc.get(), digis_d.adc(), wordCounter*sizeof(uint16_t), cudaMemcpyDefault, stream.id()));
```

**Comment by fwyzard** [comment]
The `Pixel tracks (B-hadron TPs) part` is back :-)

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.8BvpHUwJnU ...

**Pull request merged**
