### PR TITLE
Reducing number of arrays used for the error unpacking

### PR DESCRIPTION
**Pull request by calabria**
Using just one array for the error unpacking.
Some clean up.
Restore the use of unsigned char in the cabling map.
Introduce parameter to enable the error debug.

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@calabria can you make a struct for the error instead of setting four contigous integers in the same array?

**Comment by fwyzard** [comment]
I'm asking because I do not know: do we actually need to set all 4 values in the error case ?
if we do, are they all 32-bit long ?

**Comment by calabria** [comment]
yes we do, but actually not all the values are 32-bit long. I will change this

**Comment by fwyzard** [comment]
@calabria can you make the changes suggested by @felicepantaleo ?

**Comment by calabria** [comment]
I am working to use SimpleVector instead of arrays, probably it is no more needed to make those modifications.

**Comment by fwyzard** [comment]
@calabria, I've merged the change back to `unsigned char` into the branch CMSSW_10_1_X_Patatrack.
The rest has diverged too much - if it is still relevant, can you make a new PR based on the latest branch ?

**Pull request closed without merging**
