### PR TITLE
Add optional flags to disable SOA->legacy conversion and GPU->CPU transfer

### LINKED ISSUE #67: Improve the transfers of DIGIs and clusters in Raw2Cluster
#### Digis
After #62 the DIGIS+errors are still always transferred back to CPU. In the pixel tracking workflow they are not used, so it should be straightforward do make their transfer on-demand. Basically this requires moving the transfers
https://github.com/cms-patatrack/cmssw/blob/cdcd677b010bad75f67b740350e88261b2b03e1a/EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToClusterGPUKernel.cu#L645-L655
from the kernel to the "transfer function"
https://github.com/cms-patatrack/cmssw/blob/cdcd677b010bad75f67b740350e88261b2b03e1a/EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToClusterHeterogeneous.cc#L517-L518

On a longer term (going beyond the quadruplet pixel tracks), the error information will likely become useful, so one could think of splitting the DIGIs and the errors to two separate `HeterogeneousProduct`s (with the cost of them having different product labels...).

#### Clusters
The clusters, on the other hand, are needed in the CPU for various reasons (RecHits need to make edm::Refs, MC matching relies on clusters etc). After #62 the CPU clusters are first put as part of `HeterogeneousProduct`, and then copied to a standard `edmNew::DetSetVector<SiPixelCluster>` by `SiPixelClusterHeterogeneousConverter`. Since the standard collection is needed anyway, it would be more optimal to produce it directly already by `SiPixelRawToClusterHeterogeneous`. (this will then lead to a funny situation of module `siPixelDigis` taking `siPixelCluters` as an input, but ok)

### PR DESCRIPTION
**Pull request by makortel**
This PR simplifies the raw2cluster and rechits CPU output so that they are always produced (since by default the products are always needed in CPU, resolves #67). Then it adds explicit configuration flags to switch off the conversion from CPU-SOA to CPU-legacy, and the GPU->CPU transfers altogether. It also adds two customization functions extending the "profiling workflow" to disable the data conversion, and, in addition, disable the transfers.

The customize functions are useful to study the technical performance of a "what if" case where we would replace the legacy dataformats with SOAs.

@felicepantaleo @fwyzard @VinInn

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel what is the use case of disabling the conversions but not the transfers ?

**Comment by makortel** [comment]
To separate the costs of "GPU-SOA -> CPU-SOA" and "CPU-SOA -> CPU-legacy", eventually showing that the latter is very costly.

(Ok, it's a bit cheating because if we want to persist the CPU-SOA on disk, very likely we can't use the `cudaMallocHost` for that, so we'd need a `memcpy` to another CPU-SOA, but I'd expect that to be relatively cheap. OTOH, HLT doesn't need to save clusters+hits to disk)

**Comment by fwyzard** [comment]
> (Ok, it's a bit cheating because if we want to persist the CPU-SOA on disk, very likely we can't use the cudaMallocHost for that, so we'd need a memcpy to another CPU-SOA, but I'd expect that to be relatively cheap.

That's because the framework needs to own the memory ?

**Comment by fwyzard** [comment]
I hope I fixed the conflicts correctly...

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.b9OGZy6UGn ...

**Comment by fwyzard** [comment]
Seems so.
However, I would rather leave 59fe1f58d6bea7398967ca92c02b5b028d9d14b5 out of this PR.

**Comment by fwyzard** [comment]
> That one is actually a crucial part of the more slimmed customizations.

Right, I should have grepped case insensitive... I've now restored it.

**Comment by fwyzard** [comment]
> It's more for serialization by ROOT. It may be possible to serialize `cudaMallocHost`-allocated objects such that they get deserialized with `malloc`, but it is not evident (to me) how to achieve that.

OK, that's beyond my expertise - but why would it make a difference where the original memory comes from ?

Do you mean that if we use something like a `vector` with a CUDA-aware allocator, the allocator is part of the type, and ROOT needs to be aware of it ?

**Comment by fwyzard** [comment]
> In addition, in principle another reason to copy soon from non-pageable memory to regular memory on CPU is that non-pageable memory is somewhat limited resource (ok, up to ~4 GB should be relatively safe still what I've read, so I'd expect it to take some time before we hit that limit in practice).

I think we can have as much non-pageable memory as the available physical memory.
For example, on vinavx2 I could `cudaMallocHost` (and then `memset` to make sure it was really allocated) up to 14 GB.

**Comment by fwyzard** [comment]
Going back to

> It's more for serialization by ROOT. It may be possible to serialize `cudaMallocHost`-allocated objects such that they get deserialized with `malloc`, but it is not evident (to me) how to achieve that.

Reading the documentation for `cudaHostRegister`, it should be possible to create e.g. an `std::vector` without any special allocator, and register its memory buffer to CUDA / make it non-pageable (as long as it is not reallocated later on).

**Comment by makortel** [comment]
@fwyzard Replying collectively

> OK, that's beyond my expertise - but why would it make a difference where the original memory comes from ?
> 
> Do you mean that if we use something like a vector with a CUDA-aware allocator, the allocator is part of the type, and ROOT needs to be aware of it ?

Something like that. If we store struct of pointers and ints, I'd guess ROOT can't serialize it without a custom streamer. With `vector` the allocator is indeed in the type. Maybe with some custom container class we could hide the allocator.

> I think we can have as much non-pageable memory as the available physical memory.
For example, on vinavx2 I could cudaMallocHost (and then memset to make sure it was really allocated) up to 14 GB.

Ok, I'm happy to stand corrected. I just recalled people wondering in NVidia forums why they can't allocate more than ~4 GB non-pageable even if the system has more.

> Reading the documentation for cudaHostRegister, it should be possible to create e.g. an std::vector without any special allocator, and register its memory buffer to CUDA / make it non-pageable (as long as it is not reallocated later on).

While `cudaHostRegister` looks nice it is claimed to be expensive. Of course we could measure which one is more expensive, `cudaHostRegister` or `memcpy`. Another concern I have with per-event-per-module-per-EDM-stream `cudaMallocHost` or `cudaHostRegister` is a synchronization with CUDA runtime/driver(?) as I saw in #125.

**Pull request merged**
