### PR TITLE
Enable ECAL rechits reconstruction on GPUs

### PR DESCRIPTION
**Pull request by fwyzard**
Update sequences for ECAL local reconstruction running on GPU:
  - move ESProducers into the relevant cms.Tasks
  - reconstruct ECAL rechits on GPUs

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-01:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ ...

**Comment by fwyzard** [comment]
@amassiro looks like there is a problem in the copy from GPU to CPU ?

**Comment by fwyzard** [comment]
The memcheck errors are variations of
```
========= Host API memory access error at host access to 0x7f08f7f4cc00 of size 436 bytes
=========     Uninitialized access at 0x7f08f7f4cca0 on access by cudaMemcopy source.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/lib64/libcuda.so.1 (cuMemcpyDtoHAsync_v2 + 0x219) [0x293b59]
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/external/slc7_amd64_gcc820/lib/libcudart.so.10.2 [0x3940f]
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/external/slc7_amd64_gcc820/lib/libcudart.so.10.2 [0x15183]
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/external/slc7_amd64_gcc820/lib/libcudart.so.10.2 (cudaMemcpyAsync + 0x176) [0x56416]
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/lib/slc7_amd64_gcc820/pluginRecoLocalCaloEcalRecProducersPlugins.so (_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE + 0x415) [0x11d3e5]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm6stream17doAcquireIfNeededEPNS0_4impl12ExternalWorkERKNS_5EventERKNS_10EventSetupERNS_26WaitingTaskWithArenaHolderE + 0x39) [0x28df09]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm6stream21EDProducerAdaptorBase9doAcquireERKNS_14EventPrincipalERKNS_14EventSetupImplEPNS_16ActivityRegistryEPKNS_20ModuleCallingContextERNS_26WaitingTaskWithArenaHolderE + 0x121) [0x28c5f1]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm6Worker10runAcquireERKNS_14EventPrincipalERKNS_14EventSetupImplERKNS_13ParentContextERNS_26WaitingTaskWithArenaHolderE + 0x9a) [0x25d97a]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm6Worker28runAcquireAfterAsyncPrefetchEPKNSt15__exception_ptr13exception_ptrERKNS_14EventPrincipalERKNS_14EventSetupImplERKNS_13ParentContextENS_26WaitingTaskWithArenaHolderE + 0x116) [0x25daf6]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so [0x1d5027]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/external/slc7_amd64_gcc820/lib/libtbb.so.2 [0x2725d]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/external/slc7_amd64_gcc820/lib/libtbb.so.2 [0x27555]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm14EventProcessor12processLumisERKSt10shared_ptrIvE + 0x95) [0x163165]
=========     Host Frame:/data/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre8_Patatrack/lib/slc7_amd64_gcc820/libFWCoreFramework.so (_ZN3edm14EventProcessor15runToCompletionEv + 0x7ce) [0x16abde]
=========     Host Frame:cmsRun [0x12d9b]
=========     Host Frame:cmsRun (main + 0x162) [0x11362]
=========     Host Frame:/lib64/libc.so.6 (__libc_start_main + 0xf5) [0x223d5]
=========     Host Frame:cmsRun [0x11468]
```
that point to three places:
```
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/lib/slc7_amd64_gcc820/pluginRecoLocalCaloEcalRecProducersPlugins.so (_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE + 0x415) [0x11d3e5]
```
```
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/lib/slc7_amd64_gcc820/pluginRecoLocalCaloEcalRecProducersPlugins.so (_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE + 0x472) [0x11d442]
```
```
=========     Host Frame:/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/lib/slc7_amd64_gcc820/pluginRecoLocalCaloEcalRecProducersPlugins.so (_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE + 0x4cf) [0x11d49f]
```

Dumping  `pluginRecoLocalCaloEcalRecProducersPlugins.so` with 
```
objdump -d -S -l -C pluginRecoLocalCaloEcalRecProducersPlugins.so
```
and looking for the three addresses `0x11d3e5`, `0x11d442`, `0x11d49f` yields
```
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:104
  cudaCheck(cudaMemcpyAsync(recHitsEB_.chi2.data(),
  11d3c0:       49 8b 74 24 40          mov    0x40(%r12),%rsi
  11d3c5:       4c 8b 44 24 48          mov    0x48(%rsp),%r8
  11d3ca:       b9 02 00 00 00          mov    $0x2,%ecx
  11d3cf:       48 8b bb a0 02 00 00    mov    0x2a0(%rbx),%rdi
_ZNKSt6vectorIfN3cms4cuda13HostAllocatorIfLj0EEEE4sizeEv():
/data/cmssw/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/include/c++/8.4.0/bits/stl_vector.h:806
  11d3d6:       48 8b 93 a8 02 00 00    mov    0x2a8(%rbx),%rdx
  11d3dd:       48 29 fa                sub    %rdi,%rdx
_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE():
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:104
  11d3e0:       e8 9b 83 fe ff          callq  105780 <cudaMemcpyAsync@plt>
  11d3e5:       89 c5                   mov    %eax,%ebp
```
```
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:115
  cudaCheck(cudaMemcpyAsync(recHitsEB_.extra.data(),
  11d41d:       49 8b 74 24 48          mov    0x48(%r12),%rsi
  11d422:       4c 8b 44 24 48          mov    0x48(%rsp),%r8
  11d427:       b9 02 00 00 00          mov    $0x2,%ecx
  11d42c:       48 8b bb b8 02 00 00    mov    0x2b8(%rbx),%rdi
_ZNKSt6vectorIjN3cms4cuda13HostAllocatorIjLj0EEEE4sizeEv():
/data/cmssw/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/include/c++/8.4.0/bits/stl_vector.h:806
  11d433:       48 8b 93 c0 02 00 00    mov    0x2c0(%rbx),%rdx
  11d43a:       48 29 fa                sub    %rdi,%rdx
_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE():
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:115
  11d43d:       e8 3e 83 fe ff          callq  105780 <cudaMemcpyAsync@plt>
  11d442:       89 c5                   mov    %eax,%ebp
```
and
```
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:126
  cudaCheck(cudaMemcpyAsync(recHitsEB_.flagBits.data(),
  11d47a:       49 8b 74 24 50          mov    0x50(%r12),%rsi
  11d47f:       4c 8b 44 24 48          mov    0x48(%rsp),%r8
  11d484:       b9 02 00 00 00          mov    $0x2,%ecx
  11d489:       48 8b bb d0 02 00 00    mov    0x2d0(%rbx),%rdi
_ZNKSt6vectorIjN3cms4cuda13HostAllocatorIjLj0EEEE4sizeEv():
/data/cmssw/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/include/c++/8.4.0/bits/stl_vector.h:806
  11d490:       48 8b 93 d8 02 00 00    mov    0x2d8(%rbx),%rdx
  11d497:       48 29 fa                sub    %rdi,%rdx
_ZN21EcalCPURecHitProducer7acquireERKN3edm5EventERKNS0_10EventSetupENS0_26WaitingTaskWithArenaHolderE():
/data/user/fwyzard/patatrack/validation/run_473.ppMGgcIhmJ/testing/src/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc:126
  11d49a:       e8 e1 82 fe ff          callq  105780 <cudaMemcpyAsync@plt>
  11d49f:       89 c5                   mov    %eax,%ebp
_ZN3cms4cuda10cudaCheck_EPKciS2_9cudaErrorS2_():
```
so the error seems to be caused by 
https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc#L104-L108

https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc#L115-L119

https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc#L126-L130

**Comment by fwyzard** [comment]
@amassiro I've spotted three issues:
  - missing `cudaFree(...)` in https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecAlgos/src/EcalLinearCorrectionsGPU.cc#L37-L41:
```diff
index 20946028aba9..0af2a9044ab6 100644
--- a/RecoLocalCalo/EcalRecAlgos/src/EcalLinearCorrectionsGPU.cc
+++ b/RecoLocalCalo/EcalRecAlgos/src/EcalLinearCorrectionsGPU.cc
@@ -38,6 +38,10 @@ EcalLinearCorrectionsGPU::Product::~Product() {
   // deallocation
   cudaCheck(cudaFree(p1));
   cudaCheck(cudaFree(p2));
+  cudaCheck(cudaFree(p3));
+  cudaCheck(cudaFree(t1));
+  cudaCheck(cudaFree(t2));
+  cudaCheck(cudaFree(t3));
 }
 
 EcalLinearCorrectionsGPU::Product const& EcalLinearCorrectionsGPU::getProduct(cudaStream_t cudaStream) const {
```

  - the EE copies in [RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc](https://github.com/cms-patatrack/cmssw/blob/CMSSW_11_1_X_Patatrack/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc) all seem to have size 0

  - the EB copies in [RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc](https://github.com/cms-patatrack/cmssw/blob/CMSSW_11_1_X_Patatrack/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc) all seem to have larger size than the actual data, causing the "access to uninitialized memory" errors

**Comment by amassiro** [comment]
cmssw/RecoLocalCalo/EcalRecAlgos/src/EcalLinearCorrectionsGPU.cc
-> definitely a bug, thanks for spotting this.


> * the EE copies in [RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc](https://github.com/cms-patatrack/cmssw/blob/CMSSW_11_1_X_Patatrack/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc) all seem to have size 0

How did you spot this? If I look at 
"  std::cout << " [EcalCPURecHitProducer::acquire] eeRecHits.size = " << eeRecHits.size << std::endl;
"
I see non-0 size.

**Comment by fwyzard** [comment]
I've made these changes:
```diff
diff --git a/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc b/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc
index 8e1b4d399e0c..beac234fbd5d 100644
--- a/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc
+++ b/RecoLocalCalo/EcalRecProducers/plugins/EcalCPURecHitProducer.cc
@@ -90,22 +90,26 @@ void EcalCPURecHitProducer::acquire(edm::Event const& event,
   //     ./CUDADataFormats/EcalRecHitSoA/interface/RecoTypes.h:using StorageScalarType = float;
   //
 
+  std::cerr << "ebRecHits.energy from " << ebRecHits.energy << ", " << recHitsEB_.energy.size() * sizeof(::ecal::reco::StorageScalarType) << " bytes" << std::endl;
   cudaCheck(cudaMemcpyAsync(recHitsEB_.energy.data(),
                             ebRecHits.energy,
                             recHitsEB_.energy.size() * sizeof(::ecal::reco::StorageScalarType),
                             cudaMemcpyDeviceToHost,
                             ctx.stream()));
+  std::cerr << "eeRecHits.energy from " << eeRecHits.energy << ", " << recHitsEE_.energy.size() * sizeof(::ecal::reco::StorageScalarType) << " bytes" << std::endl;
   cudaCheck(cudaMemcpyAsync(recHitsEE_.energy.data(),
                             eeRecHits.energy,
                             recHitsEE_.energy.size() * sizeof(::ecal::reco::StorageScalarType),
                             cudaMemcpyDeviceToHost,
                             ctx.stream()));
 
+  std::cerr << "ebRecHits.chi2   from " << ebRecHits.chi2   << ", " << recHitsEB_.chi2.size() * sizeof(::ecal::reco::StorageScalarType)   << " bytes" << std::endl;
   cudaCheck(cudaMemcpyAsync(recHitsEB_.chi2.data(),
                             ebRecHits.chi2,
                             recHitsEB_.chi2.size() * sizeof(::ecal::reco::StorageScalarType),
                             cudaMemcpyDeviceToHost,
                             ctx.stream()));
+  std::cerr << "eeRecHits.chi2   from " << eeRecHits.chi2   << ", " << recHitsEE_.chi2.size() * sizeof(::ecal::reco::StorageScalarType)   << " bytes" << std::endl;
   cudaCheck(cudaMemcpyAsync(recHitsEE_.chi2.data(),
                             eeRecHits.chi2,
                             recHitsEE_.chi2.size() * sizeof(::ecal::reco::StorageScalarType),
diff --git a/RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc b/RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
index 1c80d648f1ee..fb4d81108064 100644
--- a/RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
+++ b/RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
@@ -301,8 +301,9 @@ void EcalRecHitProducerGPU::acquire(edm::Event const& event,
   ecal::rechit::EventInputDataGPU inputDataGPU{ebUncalibRecHits, eeUncalibRecHits};
 
   neb_ = ebUncalibRecHits.size;
+  std::cout << "Found " << ebUncalibRecHits.size << " EB uncalibrated rechits" << std::endl;
   nee_ = eeUncalibRecHits.size;
-  //   std::cout << " [EcalRecHitProducerGPU::acquire]  neb_:nee_ = " << neb_ << " : " << nee_ << std::endl;
+  std::cout << "Found " << eeUncalibRecHits.size << " EE uncalibrated rechits" << std::endl;
 
   int nchannelsEB = ebUncalibRecHits.size;  // --> offsetForInput, first EB and then EE
 
@@ -373,7 +374,9 @@ void EcalRecHitProducerGPU::produce(edm::Event& event, edm::EventSetup const& se
 
   // set the size of eb and ee
   ebRecHits.size = neb_;
+  std::cout << "Found " << ebRecHits.size << " EB calibrated rechits" << std::endl;
   eeRecHits.size = nee_;
+  std::cout << "Found " << eeRecHits.size << " EE calibrated rechits" << std::endl;
 
   // shift ptrs for ee
   eeRecHits.energy += neb_;
```

and I get

```
Begin processing the 1st record. Run 1, Event 4004, LumiSection 81 on stream 0 at 06-Jun-2020 12:49:53.800 CEST
Found 2359 EB uncalibrated rechits
Found 0 EE uncalibrated rechits
Found 2359 EB calibrated rechits
Found 0 EE calibrated rechits
ebRecHits.energy from 0x7fb552fd4c00, 9436 bytes
eeRecHits.energy from 0x7fb552fd70dc, 0 bytes
ebRecHits.chi2   from 0x7fb553c00000, 9436 bytes
eeRecHits.chi2   from 0x7fb553c024dc, 0 bytes
...
```

So, if you don't see that, maybe I made a mistake in setting up the workflow ?

**Comment by fwyzard** [comment]
The uninitialised memory accesses are due to these `return` statements inside the krnel loop over the grid:
  - https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecAlgos/src/EcalRecHitBuilderKernels.cu#L294-L300
  - https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecAlgos/src/EcalRecHitBuilderKernels.cu#L338-L340

The first fix is to change them into `continue` to let the kernel process the following elements in the loop.

However that still leaves some values not set for the affect channel.
Should there be some default values in that case ?

**Comment by amassiro** [comment]
> The uninitialised memory accesses are due to these `return` statements inside the krnel loop over the grid:
> 
> * https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecAlgos/src/EcalRecHitBuilderKernels.cu#L294-L300
> * https://github.com/cms-patatrack/cmssw/blob/709d744ee13bce30f6e724187ff06d7ec65ea460/RecoLocalCalo/EcalRecAlgos/src/EcalRecHitBuilderKernels.cu#L338-L340
> 
> The first fix is to change them into `continue` to let the kernel process the following elements in the loop.
> 
> However that still leaves some values not set for the affect channel.
> Should there be some default values in that case ?


Yes, there is the default value set before (that is then used later).

energy[ch] = -1

The return is due to the fact that previously I was setting the channel and not having a for loop.

**Comment by fwyzard** [comment]
The problem is not in the `energy`, but in the other variables like `chi2`, `extra`, *etc*.

**Comment by fwyzard** [comment]
Most issues with leaked and uninitialised memory are fixed by #475.
The issue with no rechits found in the ECAL endcap running over MV samples is pre-existing, and still being investigated; it seems to be OK in data.

**Pull request merged**
