### PR TITLE
Fix max channels

### PR DESCRIPTION
**Pull request by amassiro**
Related to issue https://github.com/cms-patatrack/cmssw/issues/478
Tests ongoing.
So far never reached 20k channels.
- unpacked: left untouched
- uncalibrechit: added protection
- rechit: added protection

Does the unpacked require a protection?

### CODE REVIEW

**Comment by fwyzard** [comment]
can you rebase it on top of the current `CMSSW_11_1_X_Patatrack` ?

**Comment by vkhristenko** [comment]
@amassiro, there are a couple of options
 - allocate for max num channels
 - deallocate and allocate 2x if reached the current max.

was not added since the beginning for simplicity. 2nd option is easy to add. i will add a pr for unpacker/uncalib separately

**Comment by amassiro** [comment]
> @amassiro, there are a couple of options
> 
> * allocate for max num channels
> * deallocate and allocate 2x if reached the current max.
> 
> was not added since the beginning for simplicity. 2nd option is easy to add. i will add a pr for unpacker/uncalib separately

Thanks!
I will then do the same for the rechit part.

In the meanwhile I rebased.

**Comment by fwyzard** [comment]
@amassiro sorry, looks like I lost this one along the way... can you remind me if it was ready to go, or if there was anything pending ?

**Comment by amassiro** [comment]
> @amassiro sorry, looks like I lost this one along the way... can you remind me if it was ready to go, or if there was anything pending ?


it was ready to go, unless there was a more refined way to add these protections.

@vkhristenko : did you create the PR for the unpacker with the options you suggested?

**Comment by vkhristenko** [comment]
@amassiro , no did not create. i take my words back, please go ahead with whichever way you prefer for that.

**Comment by fwyzard** [comment]
@amassiro what do you think we should do about this PR now that we merged #517 ?

**Comment by amassiro** [comment]
I would close this PR.
The tiny changes, if needed, will be added in a separate clean PR.

**Comment by fwyzard** [comment]
Mostly not necessary after #517, to be reimplemented if needed.

**Pull request closed without merging**
