### PR TITLE
Reorganize CUDAScopedContext

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR reorganizes `CUDAScopedContext` in two ways

1. Split `CUDAScopedContext` to `CUDAScopedContextAcquire` and `CUDAScopedContextProduce`
   * Currently `CUDAScopedContext` has a mixture of possible operations that is based on how it was constructed. This is rather error prone, e.g. I remember forgetting several times to pass `edm::WaitingTaskWithArenaHolder` to it leading to weird crashes. Now `CUDAScopedContextAcquire` always requires the holder.
2. Rename `CUDAContextToken` to `CUDAContextState`, and instead of explicitly saving the state of `CUDAScopedContextAcquire` into it, pass `CUDAContextState` to the constructor of  `CUDAScopedContextAcquire` so that the latter can save the state on its destructor.
   * This way is much safer. The pattern is somewhat similar to `std::mutex` (as member variable) and locks (local variable)

#### PR validation:

Profiling workflow runs.

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at workergpu25:/mnt/home/fwyzard/validation/run.lzceLEB2bn ...

**Comment by fwyzard** [comment]
No changes in physics performance, as expected,

**Comment by fwyzard** [comment]
No changes in performance observed on the T4:
  - reference: `981.2 ± 6.1 ev/s`
  - changed: `982.8 ± 6.8 ev/s`

**Comment by makortel** [comment]
> The only thing which is slightly confusing is the use of `CUDAScopedContextProduce` in an `EDAnalyzer::analyze()` method.
> 
> But I don't have a better name to suggest, so I'm fine with the changes.

I agree that it's a bit confusing. I could add `CUDAScopedContextAnalyze` that would differ from `CUDAScopedContextProduce` by not having the `wrap()` nor `emplace()`. If you think that would be useful, I can add it in a follow-up PR that introduces a pattern for a chain of CPU tasks and GPU "tasks" within a module.

**Comment by fwyzard** [comment]
Yes, I think that would make things even more clear,  thank you.

**Pull request merged**
