### PR TITLE
please ignore: testing cms-bot

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping @cmsbot

**Comment by smuzaffar** [comment]
please test

**Comment by felicepantaleo** [comment]
Thanks Shahzad!

**Comment by fwyzard** [comment]
Eh, now we have to define the tests...

**Comment by smuzaffar** [comment]
@fwyzard , currently I have set it up to run standard cmssw tests. Once you are ready with dedicated tests then we can update cms-bot configuration.

**Comment by fwyzard** [comment]
Yep, that's what I meant :-)

Also, how do we make it run on a dedicated machine ?

.A

**Comment by felicepantaleo** [comment]
@smuzaffar how do we specify on which machine cmsbot runs tests? 
We need to run on a machine with a GPU...

**Comment by smuzaffar** [comment]
If you have a machine with GPU then we can add it to jenkins. you need to create a local `cmsbld` account on it and add the cmsbld public key 
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzHKZxVdp5tF54BJsEOgkQ6rPbhz2w4RznhPlqIM/kmZCL+HN51ofvQPgRWya9coDuuCy2eH5+yJvAZiKRqUlm2QcdUOUmCFYqQKE8WFQVCTGMyMByOHtkf3b+2LtrktIiPp01ElyqQjvoIE++bAmnwKuf3aaK70nmWhrIAQ6BrNfC0vxnx6OOwQcNIyqNHMmi5i49oEUYnwijqm24kngy/reY+ktG3+8fvuISzDru0RKO9pyrtrNg0O772kHY3/MB7GdIgwnJ/bkAvBLa7LEQS9D0EO9TLeJWy6+0IyP5lO0D0Ovillk+0RsWuj4cS7xNnE+xhe+aohuvCP0cwhYwQ== cmsbuild@lxbuild167.cern.ch
```
in to ~cmsbld/.ssh/authorized_keys

Once we have the machine in jenkins then I can update https://github.com/cms-sw/cms-bot/blob/master/repos/cms_patatrack/cmssw/repo_config.py#L25 so that jobs for this repo can make use of new machine.

**Comment by fwyzard** [comment]
Do we need to install any specific packages - or will cmsbld take care and install things locally ?

**Comment by felicepantaleo** [comment]
@smuzaffar , the machine is `vinavx2.cern.ch`. I added the public key. Could you check if it works?

**Comment by felicepantaleo** [comment]
@smuzaffar done!

**Comment by felicepantaleo** [comment]
@smuzaffar let's do it on /data2 as /data is already full...

**Comment by smuzaffar** [comment]
please test
let see if this times tests land on `vinavx2.cern.ch`

**Comment by smuzaffar** [comment]
tests started properly on `vinavx2.cern.ch` but as default cmssw tests uses production arch i.e. `slc6_amd64_gcc630` so tests are runningf or this arch and will fail as `vinavx2` is slc7 machine.

**Comment by fwyzard** [comment]
Hi Shahzad,
how do we make cmsbot run with CC7 ?

Also, is there some kind of scheduling, to limit the amount of tests being
run at the same time, and/or the time allotted to each test ?

.A

**Comment by fwyzard** [comment]
Looks like @cmsbot is working as intended: we need to make adjustments and fix some compilation flags, but we can adjust them as we go.

**Pull request closed without merging**
