### PR TITLE
[do not merge] Synchronise with CMSSW_10_5_0_pre2

### PR DESCRIPTION
**Pull request by fwyzard**
Fix conflicts.
Update PixelFitterByRiemannParaboloid interface to match cms-sw#25838 .

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel can you check if de22c81 and  a1ca1ce look right ?

**Comment by makortel** [comment]
@fwyzard They look good to me. In https://github.com/cms-patatrack/cmssw/commit/de22c81b7235c7a217f4ee0bf65fc7ebf7ee123c, was there some specific conflict I should take a more careful look?

**Comment by fwyzard** [comment]
Thanks.
In de22c81b7235c7a217f4ee0bf65fc7ebf7ee123c, could you double check `EventFilter/SiPixelRawToDigi/python/SiPixelRawToDigi_cfi.py` and `RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py` ?

**Comment by makortel** [comment]
@fwyzard I took another look on those two files, and the diffs in https://github.com/cms-patatrack/cmssw/commit/de22c81b7235c7a217f4ee0bf65fc7ebf7ee123c look fine.

**Comment by fwyzard** [comment]
Thank you !
I will try to run the usual validation, and as soon as everything looks fine I'll start building CMSSW_10_5_0_pre2_Patatrack .

**Comment by makortel** [comment]
Thanks!

**Comment by fwyzard** [comment]
Throughput looks unchanged with respect to pre1.
### CMSSW_10_5_0_pre2_Patatrack candidate
```
Running 4 times over 4200 events with 1 jobs, each with 8 threads, 8 streams and 1 GPUs
  1900.5 ±   1.6 ev/s (4000 events)
  1891.6 ±   1.8 ev/s (4000 events)
  1884.4 ±   2.4 ev/s (4000 events)
  1899.9 ±   1.5 ev/s (4000 events)
 --------------------
  1894.1 ±   7.6 ev/s
```
vs
### CMSSW_10_5_0_pre1_Patatrack
```
Running 4 times over 4200 events with 1 jobs, each with 8 threads, 8 streams and 1 GPUs
  1898.1 ±   1.7 ev/s (4000 events)
  1890.0 ±   1.8 ev/s (4000 events)
  1898.6 ±   1.6 ev/s (4000 events)
  1895.1 ±   1.8 ev/s (4000 events)
 --------------------
  1895.5 ±   4.0 ev/s
```

**Comment by fwyzard** [comment]
### Validation summary
Reference release [CMSSW_10_5_0_pre1](https://github.com/cms-sw/cmssw/tree/CMSSW_10_5_0_pre1) at e12fca33d0bf


:construction: Validation running at workergpu20:/mnt/home/fwyzard/validation/run.Yh2j7nI0vX ...

**Comment by fwyzard** [comment]
### Validation summary
Reference release [CMSSW_10_5_0_pre1](https://github.com/cms-sw/cmssw/tree/CMSSW_10_5_0_pre1) at e12fca33d0bf
Development branch [CMSSW_10_5_X_Patatrack](https://github.com/cms-patatrack/cmssw/tree/CMSSW_10_5_X_Patatrack) at 498712aee82a


:construction: Validation running at workergpu20:/mnt/home/fwyzard/validation/run.Yh2j7nI0vX ...

**Comment by fwyzard** [comment]
### validation plots from 500 TTbar events
  - cpu workflow (10824.5): [index](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/CMSSW_10_5_0_pre2/RelValTTbar_13/10824.5/index.html) and [summary](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/CMSSW_10_5_0_pre2/RelValTTbar_13/10824.5/plots_summary.html):

  | CMSSW_10_5_0_pre1, 10824.5 | CMSSW_10_5_0_pre2, 10824.5 | CMSSW_10_5_0_pre1_Patatrack, 10824.5 | CMSSW_10_5_0_pre2_Patatrack, 10824.5
-- | -- | -- | -- | --
Efficiency | 0.4896 | 0.4896 | 0.4897 | 0.4897
Number of TrackingParticles (after cuts) | 27596 | 27596 | 27596 | 27596
Number of matched TrackingParticles | 13512 | 13512 | 13514 | 13514
Fake rate | 0.0522 | 0.0522 | 0.0523 | 0.0523
Duplicate rate | 0.0164 | 0.0164 | 0.0159 | 0.0159
Number of tracks | 161450 | 161450 | 161437 | 161437
Number of true tracks | 153026 | 153026 | 152991 | 152991
Number of fake tracks | 8424 | 8424 | 8446 | 8446
Number of pileup tracks | 134504 | 134504 | 134450 | 134450
Number of duplicate tracks | 2646 | 2646 | 2566 | 2566

  - cpu workflow (ex 10824.8): [index](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/CMSSW_10_5_0_pre2/RelValTTbar_13/10824.8/index.html) and [summary](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/CMSSW_10_5_0_pre2/RelValTTbar_13/10824.8/plots_summary.html):

  | CMSSW_10_5_0_pre1, 10824.5 | CMSSW_10_5_0_pre2, 10824.5 | CMSSW_10_5_0_pre1_Patatrack, 10824.5 | CMSSW_10_5_0_pre2_Patatrack, 10824.5
-- | -- | -- | -- | --
Efficiency | 0.4896 | 0.4896 | 0.5749 | 0.5749
Number of TrackingParticles (after cuts) | 27596 | 27596 | 27596 | 27596
Number of matched TrackingParticles | 13512 | 13512 | 15865 | 15864
Fake rate | 0.0522 | 0.0522 | 0.0338 | 0.0338
Duplicate rate | 0.0164 | 0.0164 | 0.0003 | 0.0003
Number of tracks | 161450 | 161450 | 218105 | 218105
Number of true tracks | 153026 | 153026 | 210742 | 210741
Number of fake tracks | 8424 | 8424 | 7363 | 7364
Number of pileup tracks | 134504 | 134504 | 187152 | 187152
Number of duplicate tracks | 2646 | 2646 | 62 | 62

**Pull request merged**
