### PR TITLE
Drop obsolete heterogenous framework

### PR DESCRIPTION
**Pull request by fwyzard**
Drop the obsolete attempt of a heterogeneous framework:
  - HeterogeneousCore/Producer
  - HeterogeneousCore/Product
  - HeterogeneousCore/CUDACore/*/GPUCuda.\*

and update the BuildFiles accordingly.

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-01:/data/user/fwyzard/patatrack/validation/run.h8zhPpSOVs ...

**Comment by fwyzard** [comment]
@makortel have I missed anything ?

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-01:/data/user/fwyzard/patatrack/validation/run.NZMR9k9TTc ...

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-01:/data/user/fwyzard/patatrack/validation/run.MAr1TNxVVD ...

**Comment by fwyzard** [comment]
No impact on physics or throughput, as expected.

**Comment by makortel** [comment]
> @makortel have I missed anything ?

This should be all, thanks.

**Pull request merged**
