### PR TITLE
fix gain&pede for run3

### PR DESCRIPTION
**Pull request by VinInn**
as title says...

references 

https://github.com/cms-sw/cmssw/pull/27983#discussion_r442749858

https://github.com/cms-sw/cmssw/blob/master/RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py#L7-L28

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-35-01:/data/user/fwyzard/patatrack/validation/run_492.GZDg0gthTL ...

**Comment by mmusich** [comment]
>  In principle it would be nice to have consistent configuration interface with the legacy code, but that would be a different discussion (mainly up to DPG) 

Can you elaborate what do you mean by this?

**Comment by makortel** [comment]
> > In principle it would be nice to have consistent configuration interface with the legacy code, but that would be a different discussion (mainly up to DPG)
> 
> Can you elaborate what do you mean by this?

I mean if DPG is fine with the hardcoded approach, I don't object.

**Comment by mmusich** [comment]
> I mean if DPG (or whoever takes over the maintenance) is fine with the hardcoded approach, I don't object.

The DPG (at least me) would prefer the python configurable approach, but since Vincenzo is a strong supporter of the hardcoded approach, which I believe has its advantages, I am not going to argue with it. In any case we don't expect to change these numbers again in Run-3.

**Comment by fwyzard** [comment]
Ops, when I ran the validation I forgot to actually upload the results - they should be there now.

I don't think we are able to spot the change with our validation, though ?

**Comment by VinInn** [comment]
well, a clear difference is present here
https://patatrack.web.cern.ch/patatrack/validation/pulls/026fc00a82693c66c255934d1c724c923d3e1396/RelValTTbar_14TeV-CMSSW_11_0_0_patch1-PU_110X_mcRun3_2021_realistic_v6-v1/10824.502/plots_pixel_Pt09_pixel/resolutionsPt.pdf

**Comment by fwyzard** [comment]
The differences should be between "black" (CMSSW_11_1_X_Patatrack) and "orange" (this PR), and I don't see the black points anywhere, so I'm assuming they are exactly beneath the orange ones ?

**Comment by VinInn** [comment]
This is my impression as well: black and orange identical to essentially last bit

**Comment by fwyzard** [comment]
Yes... so now I'm wondering if that is expected, or if for some reason the changes are not being exercised.

**Comment by fwyzard** [comment]
The latter:
> the changes are not being exercised

The workflows are still the ones from 2018, even though the samples are from 2021 MC !

Will fix...

**Comment by VinInn** [comment]
and that what you would expect for ```process = cms.Process('RECO',Run2_2018,gpu)
```

**Comment by fwyzard** [comment]
Yes, I remembered... the problem is that the `.5` workflow does not exist for 2021, and I haven't added it yet.

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-01:/data/user/fwyzard/patatrack/validation/run_492.zSLfd7g2CS ...

**Comment by fwyzard** [comment]
Mhm, that didn't really work very well :-(

**Comment by mmusich** [comment]
For my own education, what's the plan to integrate these changes?

**Comment by fwyzard** [comment]
The plan is
  - find some spare time
  - fix the validation workflow (see e.g. https://patatrack.web.cern.ch/patatrack/validation/pulls/cc631688d19029e160bed4215a8fa7f17f6c01f1/RelValTTbar_14TeV-CMSSW_11_0_0_patch1-PU_110X_mcRun3_2021_realistic_v6-v1/11634.502/plots_pixel_pixel/effandfakePtEtaPhi.pdf)
  - validate the changes
  - merge this PR
  - build the next Patatrack release

**Comment by fwyzard** [comment]
After running more checks both online and offline, my conclusion is that the results - and thus this change - are tied to the conditions being used:
  - using older global tags (e.g. `110X_mcRun3_2021_realistic_v6` with 11.1.x), the current parameters in the code are correct
  - using newer global tags (e.g. `112X_mcRun3_2021_realistic_v2` with 11.2.x), the new parameters should be used

@mmusich way the change does not trigger any errors ? is it because the parameters were chaged in the same type of payload ?

That seems like the "quick and dirty" solution, that is easier for whoever made the changes, and potentially causing problems everywhere else...

What is the first global tag(s) that use the new conditions ?

**Comment by mmusich** [comment]
> After running more checks both online and offline, my conclusion is that the results - and thus this change - are tied to the conditions being used

This is pretty obvious to understand when looking to the PR in which the change was proposed (that I pointed to in the discussion at https://github.com/cms-sw/cmssw/pull/27983#discussion_r442749858).

>  way the change does not trigger any errors ? is it because the parameters were chaged in the same type of payload 

Why should it trigger any errors? The payloads are totally valid, just the numbers in them have a different interpretation starting from a given pre-release (11_1_0_pre7 to be precise). The VCal calibration is included in the DB rather than in the code.

> That seems like the "quick and dirty" solution, that is easier for whoever made the changes, and potentially causing problems everywhere else...

I don't see any other way of doing it. We adjusted the code everywhere relevant and has also been spotted by us here....

> What is the first global tag(s) that use the new conditions ?

Only Run3 MC Global Tags are changed. The first ones containing the new payloads are the ones at: https://github.com/cms-sw/cmssw/pull/29333

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-01:/data/user/fwyzard/patatrack/validation/run_492.zd3ESMEfA9 ...

**Comment by fwyzard** [comment]
> This is pretty obvious to understand when looking to the PR in which the change was proposed (that I pointed to in the discussion at [cms-sw#27983 (comment)](https://github.com/cms-sw/cmssw/pull/27983#discussion_r442749858)).

Yes, I found out that it is `111X_mcRun3_2021_realistic_v4` .
 
> > way the change does not trigger any errors ? is it because the parameters were chaged in the same type of payload
> 
> Why should it trigger any errors? The payloads are totally valid, just the numbers in them have a different interpretation starting from a given pre-release (11_1_0_pre7 to be precise). The VCal calibration is included in the DB rather than in the code.

Because the *meaning* of the numbers changed.

> > That seems like the "quick and dirty" solution, that is easier for whoever made the changes, and potentially causing problems everywhere else...
> 
> I don't see any other way of doing it. We adjusted the code everywhere relevant and has also been spotted by us here....

Making a different payload *type* would have ensured that it would be automatically spotted in any affected workflow.

Instead, with this approach there is nothing that prevents people from mixing old code and new conditions (or vice versa), silently leading to wrong results.

**Comment by mmusich** [comment]
> Making a different payload type would have ensured that it would be automatically spotted in any affected workflow.

We have considered this option but we did not find it worth it.
This would have implied redoing tens of tags and scores of new tags, not counting the time spent in integrating the new payload type. 

> Instead, with this approach there is nothing that prevents people from mixing old code and new conditions (or vice versa), silently leading to wrong results.

Well, a part that this is common practice in many areas, it's extremely easy to make it correct.  Run3 uses the new convention, Run2 uses the old one.  So the only way of mixing wrong code with conditions is to use Run2 code with Run3 GTs or viceversa and I think that you can agree with me that if one does so, one accepts the risks of it...

**Comment by fwyzard** [comment]
>  So the only way of mixing wrong code with conditions is to use Run2 code with Run3 GTs or viceversa and I think that you can agree with me that if one does so, one accepts the risks of it...

... or obsolete Run 3 tags.

But thanks for spotting it also here, so we could fix it.

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-01:/data/user/fwyzard/patatrack/validation/run_492.YYAKeCLJIj ...

**Comment by fwyzard** [comment]
Looks OK to me... @VinInn could you double check the validation plots ?

**Comment by VinInn** [comment]
5 and 501 are identical to last bit (expected)
502 is (marginally) "better" which is a good sign

**Comment by fwyzard** [comment]
OK... I think the best comparison I can do is of "orange" (testing) from the last validation:
testing

vs "black" (development) from the previous one:
devel

which look identical by eye.
The comparison of the summaries is also pretty close:

  | development | testing
-- | -- | --
Efficiency | 0.6674 | 0.6674
Number of TrackingParticles (after cuts) | 5322 | 5322
Number of matched TrackingParticles | 3552 | 3552
Fake rate | 0.0272 | 0.0268
Duplicate rate | 0.0002 | 0.0002
Number of tracks | 59564 | 59560
Number of true tracks | 57946 | 57962
Number of fake tracks | 1618 | 1598
Number of pileup tracks | 52815 | 52831
Number of duplicate tracks | 12 | 12

**Pull request merged**
