### PR TITLE
[RFC] Fix synchronization in various places

### PR DESCRIPTION
**Pull request by makortel**
While rebasing #100 I got stuck for a while debugging crashes/failing asserts. One case was that `cuda-memcheck --tool racecheck` got stuck in `gpuClusterChargeCut()`. After looking the code I recalled #102 and that `__syncthreads()` with some threads returning early did not work well together. Fixing that alone did not help, so I checked all cases where we use `__syncthreads()` and attempted to fix all of those that currently return early.

In the end my problem was caused by something else, but I think we should at least discuss about these (RFC also because I'm not sure of all the details, and that racecheck still hangs).

### CODE REVIEW

**Comment by makortel** [comment]
@fwyzard I got the race check to get stuck/deadlock(?) with GTX 1080 Ti as soon as I had at least two EDM streams in a job.

**Comment by fwyzard** [comment]
Does `racecheck` work for you with these changes ?
I still see it getting stuck.

**Comment by makortel** [comment]
> Does `racecheck` work for you with these changes ?
> I still see it getting stuck.

No, it still gets stuck. I'm only submitting this PR because I did the changes (as part of figuring out what is going on) and have the understanding this way to be more correct.

(just for reference https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#synchronization-functions
> `__syncthreads()` is allowed in conditional code but only if the conditional evaluates identically across the entire thread block, otherwise the code execution is likely to hang or produce unintended side effects.

)

**Comment by fwyzard** [comment]
I agree with you on `__syncthreads()`.

I've seen some scattered comments about "non-exited threads" that suggest what we are doing may be overkill; e.g. the documentation for `__syncwarp()` states that (emphasis mine):

> All **non-exited threads** named in mask must execute a corresponding `__syncwarp()` with the same mask, or the result is undefined.

I guess this is something we need to clarify with NVIDIA.

**Comment by fwyzard** [comment]
So, here is a simple kernel that exemplifies the problem:
```c++
__global__
void test_sync(const int data[], const int size, int * result) {
  auto x = threadIdx.x + blockIdx.x * blockDim.x;

  if (x == 0)
    *result = 0;
  __syncthreads();

  if (x >= size)
    return;
  __syncthreads();

  if (x > 2 and (x % 2 == 0))
    return;
  __syncthreads();

  atomicAdd(result, 1);
} 
```

Running normally I get the expected results noth on a P100 and on a V100.

Running under `cuda-memcheck --tool syncheck` I get the expected results on a P100, while I get `0` on a V100 (with no errors being reported).

**Comment by fwyzard** [comment]
Forget about that - the issue is with `atomicAdd` misbehaving under `cuda-memcheck --tool syncheck`.

**Comment by fwyzard** [comment]
plot

**Comment by fwyzard** [comment]
Considering that (for whatever reason) these changes seem slightly slower, and that the original code seems to work fine, I would keep things as they are.

**Comment by makortel** [comment]
Our understanding is that these transformations are not needed in practice.

**Comment by felicepantaleo** [comment]
so the number of barriers reached by a thread must be exactly the same as any other non existed thread.
This might be a problem in clustering as the number of syncs depends on the local value of a `while` predicate.

**Comment by fwyzard** [comment]
The point is that all (non-exited) threads must `__syncthreads()` in the same place.
If the threads are running a different number of iterations, we need to do something like
```c++
bool active = true;
while (true) {
  if (active) {
    // only active threads work
    ...
    if (thread_is_done) {
        active = false;
    }
  }
  __syncthreads();
  if (not __syncthreads_or(active))
    break;
}
```

which can be rewritten more tersely as
```c++
bool active = true;
while (__syncthreads_or(active)) {
  if (not active) {
    continue;
  // only active threads work
  ...
  if (thread_is_done) {
    active = false;
  }
}
```
which is what we have been doing (possibly using the inverted logic, with `while (not __syncthreads_and(done))`) in the radix sort, pixel clustering, and vertex finding.

**Pull request closed without merging**
