### PR TITLE
Pixel Raw2Digi GPU version update

### PR DESCRIPTION
**Pull request by VinInn**
0) fix digi2raw in simulation to properly pack 2 uint32 in one uint64
1) digi packing ported to GPU. transfer back to host only packed digis
2) some size (to 16bits) reduction of various types (more can be done)
3) removed fed association to blocks: transfer fedId (as uint8) for a group of 2 (can 4 or 8) words padding fed if necessary (overhead (1/8 etc) can be tuned w/r/t computation in GPU)
4) fix error management (requires data to test it): seems to work not perfect though

tbd: errors should be transferred in a shorter array

### CODE REVIEW

**Comment by felicepantaleo** [comment]
Can I merge this, or you're still working on it?

**Comment by felicepantaleo** [comment]
ah, needs rebase...

**Comment by VinInn** [comment]
rebase w/r/t what?
In any case it still printing too much. tomorrow I will remove debugging

**Comment by fwyzard** [comment]
Please do not merge it... I still have to figure out what would happen, and as Vincenzo said it should be clean up first.

**Comment by felicepantaleo** [comment]
reopen...

**Comment by fwyzard** [comment]
What part of "please do not merge it" was not clear ?

**Pull request merged**
