### PR TITLE
Move multifit/MAHI common code to DataFormats/CaloRecHit

### PR DESCRIPTION
**Pull request by mariadalfonso**
mv th
DataFormats_Math_interface_EigenComputations_h into DataFormats_CaloRecHit_interface_MultifitComputations_h
fnnl appear only once in the common space to be used for both Ecal and Hcal 
as requested

### CODE REVIEW

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-01:/data/user/fwyzard/patatrack/validation/run_557.bhGHFnfw13 ...

**Comment by fwyzard** [comment]
Mhm, during the validation I got
```
1 error detected in the compilation of "/data/user/fwyzard/patatrack/validation/run_557.bhGHFnfw13/testing/src/RecoLocalCalo/EcalRecProducers/plugins/AmplitudeComputationKernels.cu".
>> Compiling LCG dictionary: tmp/slc7_amd64_gcc820/src/DataFormats/HcalRecHit/src/DataFormatsHcalRecHit/a/DataFormatsHcalRecHit_xr.cc
gmake: *** [config/SCRAM/GMake/Makefile.rules:1687: tmp/slc7_amd64_gcc820/src/RecoLocalCalo/EcalRecProducers/plugins/RecoLocalCaloEcalRecProducersPlugins/AmplitudeComputationKernels.cu.o] Error 1
```

**Comment by fwyzard** [comment]
The actual error is
```
/data/user/fwyzard/patatrack/CMSSW_11_2_0_pre7/src/RecoLocalCalo/EcalRecProducers/plugins/AmplitudeComputationKernels.cu(282): error: no instance of function template "calo::multifit::fnnls" matches the argument list
            argument types are: (calo::multifit::MapSymM<ecal::multifit::data_type, 10, 0>, ecal::multifit::SampleVector, calo::multifit::ColumnVector<10, ecal::multifit::data_type>, int, calo::multifit::ColumnVector<10, int>, calo::multifit::MapSymM<ecal::multifit::data_type, 10, 0>, double, int)
```

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-01:/data/user/fwyzard/patatrack/validation/run_557.ctoko59zZx ...

**Comment by fwyzard** [comment]
@mariadalfonso do the changes look OK to you ?

**Comment by mariadalfonso** [comment]
> @mariadalfonso do the changes look OK to you ?

yes, of course, good for me

**Comment by fwyzard** [comment]
:construction: Validation running at fu-c2a02-37-02:/data/user/fwyzard/patatrack/validation/run_557.nSmY3GpjTJ ...

**Pull request merged**
