### PR TITLE
CTD19 developments for review and merging (fixed)

### PR DESCRIPTION
**Pull request by VinInn**
This PR on top of #324 
1) merges #327 and #328
2) fixes a major bug introduced when using cache allocator for cub workspace
3) fixes two long-standing issues happening in data only
3a) more then 256 hits in a module
3b) duplicate pixels

### CODE REVIEW

**Comment by VinInn** [comment]
it continues to crash if many 8-threads jobs are run concurrently see for instance
```
ls -ls ~/data/crash*
56 -rw-r--r--. 1 innocent zh 56416 Apr 23 10:27 /afs/cern.ch/user/i/innocent/data/crash1@VZ0.log
48 -rw-r--r--. 1 innocent zh 48416 Apr 23 10:28 /afs/cern.ch/user/i/innocent/data/crash2@VZ0.log
55 -rw-r--r--. 1 innocent zh 55462 Apr 23 10:32 /afs/cern.ch/user/i/innocent/data/crash3@VZ0.log
```

**Comment by VinInn** [comment]
and crashes on V100 as well

**Comment by fwyzard** [comment]
what gpu is there on vinzen0 ?

**Comment by VinInn** [comment]
> what gpu is there on vinzen0 ?
gtx1060

**Comment by fwyzard** [comment]
OK, so the multi-job crash happens on Pascal-based cards as well.
So far it has been difficult to reproduce it on a GTX 1080, now I'm stressing a P100.

**Comment by VinInn** [comment]
> 
> OK, so the multi-job crash happens on Pascal-based cards as well.
> So far it has been difficult to reproduce it on a GTX 1080, now I'm stressing a P100.
> 
I run 4x8-threads on a 8cpu node against a small gtx1060

on V100 crashes just one  8-thread job (but on flatiron, not sure if there is other activity: the system is pretty overloaded these days)
oopps in this moment I share a machine with you: workergpu16, so no real surprise

**Comment by fwyzard** [comment]
> oopps in this moment I share a machine with you: workergpu16, so no real surprise

but we should not be able to share the GPU, so it should not be an issue...

**Comment by fwyzard** [comment]
OK, it's reproducible also on a P100.

By the way, in my tests the error always points to [this line](https://github.com/cms-patatrack/cmssw/blob/e0169a3/HeterogeneousCore/CUDAServices/src/CachingDeviceAllocator.h#L598):
```c++
if (CubDebug(error = cudaEventRecord(search_key.ready_event, search_key.associated_stream))) return error;
```

And, if I add something like
```c++
if (CubDebug(error = cudaGetLastError())) return error;
```
right before it, that never triggers, and the error stays with the `cudaEventRecord()` call.

**Comment by VinInn** [comment]
@fwyzard , did you got the crashes with this PR or the current HEAD?

**Comment by VinInn** [comment]
[innocent@workergpu21 src]$ git diff
diff --git a/RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py b/RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py
index 1021918c0ce..f50ab120671 100644
--- a/RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py
+++ b/RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py
@@ -32,6 +32,6 @@ def customizePixelTracksForProfilingDisableTransfer(process):

     # Disable "unnecessary" transfers to CPU
     process.pixelTracksHitQuadruplets.gpuEnableTransfer = False
-    process.pixelVertices.gpuEnableTransfer = False
+    process.pixelVertices.gpuEnableTransfer = True

     return process


same behaviour 
crashes eventually (less then before seen even a multigpu job ending)






> On 23 Apr, 2019, at 4:06 PM, Andrea Bocci <notifications@github.com> wrote:
> 
> oopps in this moment I share a machine with you: workergpu16, so no real surprise
> 
> but we should not be able to share the GPU, so it should not be an issue...
But apparently is an issue...  (btw is your jobs still running ok?)
It crashes occasionally on an empty machine as well ...

so now I asked for 4 gpus to get a maachine on my own (flatiron is now pretty empty)
and for the first tiem in a week I manged to finish the benchmark


still it even crashed single threaded while distructing things
dropped waiting message count 0
>>> processed 13608 events
||Counters | nEvents | nHits | nCells | nTuples | nGoodTracks | nUsedHits | nDupHits | nKilledCells | nEmptyCells | nZeroTrackCells ||
/mnt/home/innocent/CMSSW_10_6_0_pre2_Patatrack/src/HeterogeneousCore/CUDAServices/src/CUDAService.cc, line 358: cudaErrorIllegalAddress: an illegal memory access was encountered

ok apparently it is using more than one device...
Exception Message:
Callback of CUDA stream 0x2aab109132b0 in device 3 error cudaErrorIllegalAddress: an illegal memory access was encountered


how to tell to use only one device?

**Comment by makortel** [comment]
> how to tell to use only one device?

With `CUDA_VISIBLE_DEVICES` environment variable (e.g. in bash `CUDA_VISIBLE_DEVICES=0 cmsRun ...`).

**Comment by fwyzard** [comment]
> did you got the crashes with this PR or the current HEAD?

With the current HEAD, running with 5 jobs with 3 streams each, all on a
single gpu.

Instead, running with one job per GPU does not crash even after 500+ tests.

.A

**Comment by VinInn** [comment]
w/o smart cache does not crash single job on V100.
continues to happily crash multi job on gtx1060

**Comment by VinInn** [comment]
But it does not crash multi job on V100....

**Comment by fwyzard** [comment]
Superseded by #338.

**Pull request closed without merging**
