### PR TITLE
Add B-hadron MTV variation to pixel track validation sequence

### PR DESCRIPTION
**Pull request by makortel**
@VinInn

### CODE REVIEW

**Comment by makortel** [comment]
At some point we (I?) should take the effort to port all the non-GPU related MTV configuration changes to CMSSW master.

**Comment by VinInn** [comment]
Thanks!

**Comment by VinInn** [comment]
included in #197

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.pkjw5XSgof ...

**Comment by fwyzard** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fwyzard/patatrack/validation/run.wIyblRCCal ...

**Comment by fwyzard** [comment]
Included via #199

**Pull request closed without merging**
