### PR TITLE
Various updates to pixel track/vertex DQM and MTV

### PR DESCRIPTION
**Pull request by makortel**
* Add DQM for pixel vertices
* Add pT > 0.9 GeV pixel tracks to MTV
* Add dzPV0p1, Pt0to1, Pt1 variants of pixel track DQM

### CODE REVIEW

**Comment by felicepantaleo** [comment]
:construction: Validation running at vinavx2.cern.ch:/data/user/fpantale/patatrack-validation/run.oyFq2vsDdl ...

**Comment by fwyzard** [comment]
I don't know what is the difference between "Reviewers" and "Assignees" for a PR...

**Comment by felicepantaleo** [comment]
@makortel for the last commit 6f8b727 , are you planning to add the plots to the MTV? I see them in the harvested root file. If not we can merge this PR

**Comment by felicepantaleo** [comment]
You can see here some sample plots produced with this PR: https://fpantale.web.cern.ch/fpantale/CTD19/PR285/

**Comment by makortel** [comment]
>  for the last commit [6f8b727](https://github.com/cms-patatrack/cmssw/commit/6f8b727eab9f3e08996dbc363c38dc92fd0ec34c) , are you planning to add the plots to the MTV? I see them in the harvested root file. If not we can merge this PR

I'm not planning to add them to MTV plotting scripts. Those histograms are part of the tracking DQM, and while adding (some of the) DQM histograms to MTV plotting could be useful, that would take longer to do and thus I think is outside of this PR.

**Comment by felicepantaleo** [comment]
thanks!

**Pull request merged**
