### PR TITLE
Gpu gain calibs

### PR DESCRIPTION
**Pull request by VinInn**
this is the branch that compiles and work works

to run it add to your config

```
process.siPixelDigis = cms.EDProducer("SiPixelRawToDigiGPU",
    CablingMapLabel = cms.string(''),
    ConvertADCtoElectrons = cms.bool(False),
    ErrorList = cms.vint32(29),
    IncludeErrors = cms.bool(True),
    InputLabel = cms.InputTag("rawDataCollector"),
    Regions = cms.PSet(

    ),
    Timing = cms.untracked.bool(False),
    UsePhase1 = cms.bool(True),
    UsePilotBlade = cms.bool(False),
    UseQualityInfo = cms.bool(False),
    UserErrorList = cms.vint32(40)
)

process.siPixelRecHitsPreSplitting = cms.EDProducer("SiPixelRecHitGPU",
    src = cms.InputTag('siPixelClustersPreSplitting'),
#    src = cms.InputTag("siPixelClusters"),
    CPE = cms.string('PixelCPEFast'),   # Generic'),
    VerboseLevel = cms.untracked.int32(0),
)


# to ensure reproducibility
process.siPixelClustersPreSplitting.payloadType = 'HLT'

# load HLT payload
process.GlobalTag = GlobalTag(process.GlobalTag, '100X_dataRun2_asv2plusPixelGainfromHLT_v1', '')
```

### CODE REVIEW

**Comment by fwyzard** [comment]
@VinInn does the branch
cms-patatrack/VinInn_gpuGainCalibs_101x
look ok ?

**Comment by fwyzard** [comment]
See https://github.com/cms-sw/cmssw/compare/master...cms-patatrack:VinInn_gpuGainCalibs_101x?expand=1 .

**Comment by fwyzard** [comment]
I meant - see
https://github.com/cms-patatrack/cmssw/compare/CMSSW_10_1_X_Patatrack...cms-patatrack:VinInn_gpuGainCalibs_101x?expand=1

**Comment by fwyzard** [comment]
If I'm not mistaked can recreate with something like
```
git checkout CMSSW_10_0_X_Patatrack
git checkout CMSSW_10_1_X_Patatrack
git checkout gpuGainCalibs
git checkout -b gpuGainCalibs_101x
git rebase -p CMSSW_10_0_X_Patatrack gpuGainCalibs_101x --onto CMSSW_10_1_X_Patatrack
```

**Comment by VinInn** [comment]
cms-patatrack/VinInn_gpuGainCalibs_101x
looks ok

**Comment by VinInn** [comment]
obsolete

**Comment by fwyzard** [comment]
superseded by #13

**Pull request closed without merging**
