### PR TITLE
Cleanup for the framework PR

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

While preparing a PR for CMSSW `master` I noticed that the unit tests (within the "framework" part) were not fully working on a non-GPU machine. As a subsequent cleanup this PR proposes
- remove an unnecessary import of the `gpu` Modifier in `testCUDASwitch_cfg.py`, and fix an input configuration parameter relevant when running without GPU
- remove `testCUDA_cfg.py` as not really useful
- rename `exitSansCUDADevices.cc` to `requireCUDADevices.cc` for consistency

Then I realized that at least with catch2 unit test framework just exiting the program in `requireCUDADevices()` is too harsh, especially when a subset of the tests (in a file) would be useful to run without GPUs. Therefore I added `hasCUDADevices()` that returns a `bool`, which allows me to `return` instead of `exit()` from catch2 tests.

#### PR validation:

Code compiles, unit tests run on both non-GPU and GPU machines.

### CODE REVIEW

**Comment by fwyzard** [comment]
> Then I realized that at least with catch2 unit test framework just exiting the program in `requireCUDADevices()` is too harsh, especially when a subset of the tests (in a file) would be useful to run without GPUs.

Do we have examples of this (running a subset of the tests without GPUs) ?

**Comment by makortel** [comment]
> > Then I realized that at least with catch2 unit test framework just exiting the program in `requireCUDADevices()` is too harsh, especially when a subset of the tests (in a file) would be useful to run without GPUs.
> 
> Do we have examples of this (running a subset of the tests without GPUs) ?

https://github.com/cms-patatrack/cmssw/blob/832e57fba88eb123a94751361b0ac01cfb952b54/CUDADataFormats/Common/test/test_CUDAProduct.cc#L25-L33
and
https://github.com/cms-patatrack/cmssw/blob/832e57fba88eb123a94751361b0ac01cfb952b54/HeterogeneousCore/CUDATest/test/test_TestCUDAProducerGPUFirst.cc#L15-L54

**Comment by makortel** [comment]
Ok, neither of them is really testing essential functionality (on a non-GPU machine).

On the other hand, demonstrating that a test CUDA producer can be constructed and ran through lumi and run transitions without a GPU has some value (since that is what actually happens today with SwitchProducer).

Alternatively we could have separate unit test executables for GPU and non-GPU cases.

**Comment by fwyzard** [comment]
@makortel I don't mind adding the extra possibility - however I'm confused about the tests themselves...

In `test_CUDAProduct.cc` there is only one test, so what is the difference from just `return` vs `exit()` ?

In `test_TestCUDAProducerGPUFirst.cc` there are multiple SECTIONs, so I guess there it makes sense.

But more importantly, what do you mean by 
> a test CUDA producer can be constructed and ran through lumi and run transitions without a GPU has some value (since that is what actually happens today with SwitchProducer).

?
I thought the SwitchProducer would only call one of the two modules (the CUDA one if we have a GPU, the non-CUDA otherwise).

**Comment by makortel** [comment]
> In `test_CUDAProduct.cc` there is only one test, so what is the difference from just `return` vs `exit()` ?

With `return` the `main()` of catch2 can finish and report successful tests in stdout. With `exit()` the program just quits (with proper exit code though).

> > a test CUDA producer can be constructed and ran through lumi and run transitions without a GPU has some value (since that is what actually happens today with SwitchProducer).
> 
> ?
> I thought the SwitchProducer would only call one of the two modules (the CUDA one if we have a GPU, the non-CUDA otherwise).

Right, but that only applies to event transitions (i.e. `produce()` etc). Construction+destruction and run+lumi transitions take place for all modules that are in Tasks/Sequences via Paths and EndPaths that are specified in Schedule (or all paths if there is no Schedule). I fully agree this is confusing, see issue cms-sw#26438.

**Comment by fwyzard** [comment]
>  I fully agree this is confusing, see issue cms-sw#26438.

Oh. Yes, yes, it is.

**Pull request merged**
